CMN_LANGUAGES={ 
'created_by': {'background':'','datatype':'NUMBER','datasegment':'BYTE','displayed':False,'enabled':False,'formatmask':'','insertallowed':True,'canvas':'','itemname':'CREATED_BY','tab':'','lov':'','maxlength':'16','multiline':False,'primarykey':False,'prompt':'Created By','rangehight':'','rangelow':'','required':False,'updateallowed':True,'updateifnull':False,'visible':False,'xpos':'0.000','ypos':'0.000' }, 
'delete_flag': {'background':'','datatype':'CHAR','datasegment':'BYTE','displayed':False,'enabled':False,'formatmask':'','insertallowed':True,'canvas':'','itemname':'DELETE_FLAG','tab':'','lov':'','maxlength':'1','multiline':False,'primarykey':False,'prompt':'Delete Flag','rangehight':'','rangelow':'','required':False,'updateallowed':True,'updateifnull':False,'visible':False,'xpos':'0.000','ypos':'0.000' }, 
'creation_date': {'background':'','datatype':'DATE','datasegment':'BYTE','displayed':False,'enabled':False,'formatmask':'','insertallowed':True,'canvas':'','itemname':'CREATION_DATE','tab':'','lov':'','maxlength':'11','multiline':False,'primarykey':False,'prompt':'Creation Date','rangehight':'','rangelow':'','required':False,'updateallowed':True,'updateifnull':False,'visible':False,'xpos':'0.000','ypos':'0.000' }, 
'last_update_date': {'background':'','datatype':'DATE','datasegment':'BYTE','displayed':False,'enabled':False,'formatmask':'','insertallowed':True,'canvas':'','itemname':'LAST_UPDATE_DATE','tab':'','lov':'','maxlength':'11','multiline':False,'primarykey':False,'prompt':'Last Update Date','rangehight':'','rangelow':'','required':False,'updateallowed':True,'updateifnull':False,'visible':False,'xpos':'0.000','ypos':'0.000' }, 
'last_updated_by': {'background':'','datatype':'NUMBER','datasegment':'BYTE','displayed':False,'enabled':False,'formatmask':'','insertallowed':True,'canvas':'','itemname':'LAST_UPDATED_BY','tab':'','lov':'','maxlength':'16','multiline':False,'primarykey':False,'prompt':'Last Updated By','rangehight':'','rangelow':'','required':False,'updateallowed':True,'updateifnull':False,'visible':False,'xpos':'0.000','ypos':'0.000' }, 
'record_status': {'background':'','datatype':'CHAR','datasegment':'BYTE','displayed':False,'enabled':False,'formatmask':'','insertallowed':True,'canvas':'','itemname':'RECORD_STATUS','tab':'','lov':'','maxlength':'1','multiline':False,'primarykey':False,'prompt':'Record Status','rangehight':'','rangelow':'','required':False,'updateallowed':True,'updateifnull':False,'visible':False,'xpos':'0.000','ypos':'0.000' }, 
'update_source': {'background':'','datatype':'CHAR','datasegment':'BYTE','displayed':False,'enabled':False,'formatmask':'','insertallowed':True,'canvas':'','itemname':'UPDATE_SOURCE','tab':'','lov':'','maxlength':'30','multiline':False,'primarykey':False,'prompt':'Update Source','rangehight':'','rangelow':'','required':False,'updateallowed':True,'updateifnull':False,'visible':False,'xpos':'0.000','ypos':'0.000' }, 
'language_code': {'background':'r255g255b255','datatype':'CHAR','datasegment':'BYTE','displayed':True,'enabled':True,'formatmask':'','insertallowed':True,'canvas':'MAINCANVAS','itemname':'LANGUAGE_CODE','tab':'','lov':'','maxlength':'10','multiline':False,'primarykey':True,'prompt':'Code','rangehight':'','rangelow':'','required':True,'updateallowed':False,'updateifnull':False,'visible':True,'xpos':'2.000','ypos':'22.000' }, 
'language_name': {'background':'r255g255b255','datatype':'CHAR','datasegment':'BYTE','displayed':True,'enabled':True,'formatmask':'','insertallowed':True,'canvas':'MAINCANVAS','itemname':'LANGUAGE_NAME','tab':'','lov':'','maxlength':'100','multiline':False,'primarykey':False,'prompt':'Name','rangehight':'','rangelow':'','required':False,'updateallowed':True,'updateifnull':False,'visible':True,'xpos':'78.000','ypos':'22.000' }, 
'fields':['created_by','delete_flag','creation_date','last_update_date','last_updated_by','record_status','update_source','language_code','language_name',],
'headers':['Created By','Delete Flag','Creation Date','Last Update Date','Last Updated By','Record Status','Update Source','Code','Name',],
}
