AP_INVOICE_HEADERS = {
    'fields': ['billto_location_id', 'invoice_user_id', 'shipto_location_id', 'po_header_id', 'grn_id', 'delete_flag',
               'update_source', 'sup_supplier_id', 'gross_total', 'creation_date', 'created_by', 'bu_id', 'invoice_id',
               'last_update_date', 'last_updated_by', 'invoice_type', 'batch_name', 'trans_category',
               'supplier_address', 'invoice_received_date', 'invoice_date', 'voucher_num', 'carriage_total',
               'discount_total', 'paid_total', 'balance_total', 'vat_total', 'net_total', 'file_name',
               'gl_accounting_date', 'description', 'invoice_currency_code', 'cpt_id', 'pmnt_method_id',
               'approved_amount', 'payment_currency_code', 'exchange_rate', 'notes1', 'notes2', 'invoice_number',
               'po_number', 'grn_number', 'dbnote_id', 'po_date', 'grn_date', 'invoice_status', 'cancelled_amount',
               'invoice_status_date', 'cancelled_by', 'cancelled_date', 'authorized_by', 'gl_account_code',
               'gl_account_id', ],
    'headers': ['Billto Location Id', 'Invoice User Id', 'Shipto Location Id', 'Po Header Id', 'Grn Id', 'Delete Flag',
                'Update Source', 'Sup Supplier Id', 'Gross Total', 'Creation Date', 'Created By', 'Bu Id', 'Invoice Id',
                'Last Update Date', 'Last Updated By', 'Type', 'Batch', 'Category', 'Supplier Address', 'Received Date',
                'Invoice Date', 'Supplier Invoice', 'Carriage Total', 'Discount Total', 'Paid Total', 'Balance Total',
                'Vat Total', 'Net Total', 'File Name', 'GL Date', 'Description', 'Currency', 'Payment  Terms',
                'Payment Method', 'Approved Amount', 'Payment Currency', 'ExchangeRate', 'Notes1', 'Notes2',
                'Invoice Number', 'PO Number', 'GRN Number', 'DBN ID', 'PO Date', 'GRN Date', 'Status',
                'Cancelled Amount', '', 'Cancelled By', 'Cancelled On', 'Authorized By', 'GL Code', 'GL Code', ],
}
AP_OPTIONS = {
    'fields': ['bu_id', 'created_by', 'delete_flag', 'creation_date', 'last_update_date', 'last_updated_by',
               'record_status', 'update_source', 'ap_options_id', 'supplier_id', 'cost_price_formula',
               'print_output_path', 'printer_id', 'printer_copies', 'billto_location_id', 'shipto_location_id',
               'batch_format', 'supplier_numbering', 'add_outsorder_qty', 'goods_in_qty_to_zero', 'follow_up_po',
               'calculate_suggested_order', 'auto_dbn_from_grn', 'auto_batch_on_grn', 'rejection_sub_location_name',
               'grn_unapproved_sub_location', 'grn_approved_sub_location', 'print_supplier_note1',
               'print_supplier_note2', 'print_split_case', 'print_note_criteria', 'items_receipt_type',
               'what_price_to_grn', 'what_price_to_po', 'suggested_qty_formula', 'suggested_formula_text',
               'invoice_matching_option', 'cpt_id', 'pmnt_method_id', 'invoice_image_path', 'bank_account_id', ],
    'headers': ['Bu Id', 'Created By', 'Delete Flag', 'Creation Date', 'Last Update Date', 'Last Updated By',
                'Record Status', 'Update Source', 'ID', 'Supplier', 'Cost Price Formula', 'Output Path', 'Printer',
                'Printer Copies', 'Bill To Location', 'Ship To Location', 'Batch Format', 'Supplier Numbering',
                'Add Outstanding Order Qty', 'Goods In Qty To Zero', 'Allow Follow Up PO', 'Calculate Suggested Order',
                'Auto DBN from GRN ', 'Auto BATCH from GRN ', 'Rejection GRN Sub Location',
                'Un-Approved GRN  Sub Location', 'Approved GRN Sub Location', 'Print Supplier Note1 ',
                'Print Supplier Note2 ', 'Print Split Case ', 'Print Criteria', 'Items Receipt Type',
                'What Price To GRN', 'What Price To PO', 'Suggested Qty Formula', 'Suggested  Formula Text',
                'Invoice Matching Option', 'Payment Term', 'Payment Method', 'Invoice Image Path', '', ],
}
AR_CUSTOMERS = {
    'fields': ['customer_id', 'customer_number', 'customer_name', 'ctp_cust_profile_id', 'cust_title',
               'contact_forename', 'contact_surname', 'contact_full_name', 'cpt_cpt_id', 'currency_code',
               'language_code', 'customer_markupdown', 'ipt_price_type_id', 'export_customer', 'ctc_tax_code_id',
               'cust_vatregno', 'phone1', 'phone2', 'fax', 'mobile', 'email', 'www', 'picturename', 'location_id',
               'billto_address_line1', 'billto_address_line2', 'billto_address_line3', 'billto_city', 'billto_county',
               'billto_post_code', 'billto_country_code', 'shipto_address_type', 'shipto_address_line1',
               'shipto_address_line2', 'shipto_address_line3', 'shipto_city', 'shipto_county', 'shipto_post_code',
               'shipto_country_code', 'shipto_email', 'shipto_contact_name', 'account_allowed', 'consolidate_items',
               'print_customer_name', 'reserve_item', 'take_deposit', 'min_deposit_amount', 'customer_hold',
               'hold_reason', 'cust_credit_limit', 'customer_class_code', 'min_value', 'customer_type_code',
               'max_value', 'rrp_percentage', 'backorder_header_id', 'print_price_type_id', 'customer_category',
               'invoiced_amount', 'paid_amount', 'balance', 'attribute1', 'attribute2', 'gl_account_id', 'supplier_id',
               'login_name', 'cust_password', 'upload_items', 'upload_instock_items', 'min_item_su_type',
               'item_pop_method', 'min_item_su_value', 'export_header_list', 'export_column_list', 'job_id',
               'www_markupdown', 'www_price_type_id', 'www_customer_category', 'www_subscription_preference',
               'www_min_order_value', 'www_min_order_freeship', 'www_start_date', 'www_end_date',
               'www_price_break_display', 'www_sub_source_id', 'www_price_incshipping', 'www_shipping_hint',
               'price_import_hint', 'ftp_user_name', 'ftp_password', 'ftp_server', 'ftp_port', 'ftp_service_provider',
               'ftp_contact', 'host_image_path1', 'host_image_path2', 'last_update_date', 'last_updated_by',
               'record_status', 'delete_flag', 'created_by', 'creation_date', 'update_source', 'bu_id',
               'primary_customer_id', 'pmnt_method_id', 'freight_header_id', 'freight_line_id', 'picturetype', ],
    'headers': ['ID', 'Number', 'Name', 'Profile', 'Title', 'First Name', 'Last Name', 'Full Name', 'Payment Terms',
                'Currency', 'Language', 'Mark Up/Down', 'On', 'Export Customer ?', 'TAX Code', 'VAT Reg No', 'Phone1',
                'Phone2', 'Fax', 'Mobile', 'Bill To Email', 'Www', 'Picture Name', '', 'Address ', '2', '3', 'City',
                'County', 'Post Code', 'Country Code', 'Type', 'Address', '2', '3', 'City', 'County', 'Post Code',
                'Country Code', 'Eamil', 'Contact Name', 'Account Payment Allowed ?', 'Consolidate Items ?',
                'Print Customer Name ?', 'Reserve Item ?', 'Take Deposit ?', 'Amount', 'Hold', ' Reason',
                'Credit Limit', 'Classification', 'Min Value', 'Type', 'Max Value', 'RRP %', 'Back Order Id',
                'Secondary Price', 'Category', 'Invoiced Amount', 'Paid Amount', 'Balance', 'Alert on Invoice',
                'Notes / Descriptions', 'GL A/C Code', '', 'Login Name', 'Password', 'Upload Items ?', 'In Stock Only?',
                'Min Sales UnitType', 'Populate Items', 'Min Sales UnitValue', 'Export Header List',
                'Export Column List', '', 'Mark Up/Down', 'On', 'Category', 'Subscription', 'Min Order Value',
                'Free Ship', 'Start Date', 'End Date', 'Show Price Break', 'Source', 'Price Incl Shipping ?',
                'Shipping Hint', 'Price  Hint', 'User Name', 'Password', 'Server', 'Server', 'Service Provider',
                'Contact ', 'Image Path1 ', 'Image Path2 ', 'Last Update Date', 'Last Updated By', 'Record Status',
                'Delete Flag', 'Created By', 'Creation Date', 'Update Source', 'Bu Id', '', 'Default Payment Method',
                'Default Payment Method', 'Default Payment Method', '', ],
}
AR_CUSTOMER_PROFILES = {
    'fields': ['bu_id', 'delete_flag', 'created_by', 'creation_date', 'last_update_date', 'last_updated_by',
               'record_status', 'update_source', 'cust_profile_id', 'cust_profile_name', 'account_allowed',
               'upload_items', 'consolidate_items', 'print_customer_name', 'reserve_item', 'take_deposit',
               'export_customer', 'cpt_cpt_id', 'min_deposit_amount', 'customer_class_code', 'tax_code_id', 'min_value',
               'customer_type_code', 'max_value', 'customer_category', 'gl_account_id', 'item_pop_method',
               'min_item_su_value', 'www_markupdown', 'www_price_type_id', 'www_customer_category',
               'www_subscription_preference', 'www_min_order_value', 'www_min_order_freeship', 'www_start_date',
               'www_end_date', 'www_price_break_display', 'end_date', 'rrp_percentage', 'upload_instock_items',
               'min_item_su_type', ],
    'headers': ['Bu Id', 'Delete Flag', 'Created By', 'Creation Date', 'Last Update Date', 'Last Updated By',
                'Record Status', 'Update Source', 'ID', 'Profile', 'Account Payment Allowed ?', 'Upload Items ?',
                'Consolidate Items ?', 'Print Customer Name ?', 'Reserve Item ?', 'Take Deposit ?', 'Export ?',
                'Payment Terms', 'Amount', 'Classification', 'Tax Code', 'Min Sales Value', 'Type', 'Max Sales Value',
                'Category', 'GL A/C Code', 'Populate Items', 'Min Sales UnitValue', 'Mark Up/Down', 'On', 'Category',
                'Subscription', 'Min Order Value', 'Free Ship', 'Start Date', 'End Date', 'Show Price Break',
                'Profile End Date', 'RRP %', 'In Stock Only?', 'Min Sales UnitType', ],
}
AR_CUST_BARCODE_UPLOADS = {
    'fields': ['upload_barcode_id', 'customer_id', 'item_id', 'su_id', 'last_update_date', 'last_updated_by',
               'creation_date', 'created_by', 'bu_id', 'delete_flag', 'update_source', 'last_upload_date',
               'record_status', 'upload_id', 'barcode', 'sales_unit', 'price_inctax', 'price_exltax', ],
    'headers': ['Upload Barcode Id', 'Customer Id', 'Item Id', 'Su Id', 'Last Update Date', 'Last Updated By',
                'Creation Date', 'Created By', 'Bu Id', 'Delete Flag', 'Update Source', 'Last Upload Date',
                'Record Status', 'Upload Id', 'Barcode', 'Min Sales Unit', 'Price Inctax', 'Price Exltax', ],
}
AR_CUST_ITEM_UPLOADS = {
    'fields': ['upload_id', 'customer_id', 'item_id', 'creation_date', 'created_by', 'bu_id', 'delete_flag',
               'update_source', 'upload_item', 'sales_unit', 'max_publish_qty', 'web_export_hint',
               'web_preference_code', 'upload_status', 'start_date_active', 'end_date_active', 'item_number_disp1',
               'item_name_disp1', 'last_upload_date', 'last_updated_by', 'last_update_date', 'record_status',
               'item_number', 'short_desc', 'long_desc', 'www_barcode', 'www_parentsku', 'www_relationship_type',
               'www_variation_theme', 'www_size_color', 'www_size_color_map', 'www_parentage', ],
    'headers': ['Upload Id', 'Customer Id', 'Item Id', 'Creation Date', 'Created By', 'Bu Id', 'Delete Flag',
                'Update Source', 'Upload ?', 'Min SU', 'Max Qty', 'Hint to WEB', 'Preference', 'Upload Status',
                'Date From', 'Date To', 'Item number', 'Item Name', 'Last Upload Date', 'Last Updated By',
                'Last Update Date', 'Record Status', 'Web SiteItem Number', 'Short Description (100 Char)',
                'Long Description (2000 Char)', 'Barcode :', 'Parent SKU :', 'Relationship Type :', 'Variation Theme :',
                'Package Quantity :', 'Design / Pattern :', 'Parentage :', ],
}
AR_OPTIONS = {
    'fields': ['bu_id', 'created_by', 'delete_flag', 'creation_date', 'last_update_date', 'record_status',
               'last_updated_by', 'update_source', 'ar_option_id', 'customer_id', 'price_type_id',
               'offer_price_type_id', 'return_sub_location_id', 'return_location_id', 'invoice_report_format',
               'invoice_screen_format', 'cpt_id', 'pmnt_method_id', 'bank_account_id', 'gl_account_id',
               'sales_order_type', 'gl_cashingup_by', 'special_offer_hint', 'document_path', 'customer_numbering',
               'barcode_qty_hint', 'inv_requisition_hint', 'allocate_order_qty', 'quantity_popup',
               'display_invnumber_onfinalise', 'populate_invoice_batch', 'surcharge_account_customers',
               'write_invoice_to_file', 'central_payment', 'pay_inout_slip', 'print_customer_note1',
               'print_customer_note2', 'print_customer_note3', 'apply_offer_on_custprice', 'print_output_path',
               'printer1_id', 'printer1_preview_mode', 'printer1_batch_mode', 'printer1_execution_mode',
               'printer1_format', 'printer1_copies', 'printer2_id', 'printer2_copies', 'printer2_preview_mode',
               'printer2_format', 'printer2_batch_mode', 'printer2_execution_mode', 'receipt_printer_id',
               'quickcode_id', 'fo_price_basis', 'credit_limit_control', 'unit_cost_plus_percent', 'noof_layaways',
               'default_item_filter', 'logoff_timeout', 'must_select_customer', 'can_change_customer',
               'print_bo_receipt', 'log_off_after_each_trans', 'duplicate_customer_name', 'print_batch_count',
               'allow_minus_stock', 'allow_part_invoice', 'monitor_layaway', 'alert_less_then_cost', 'www_markupdown',
               'www_price_type_id', 'www_customer_category', 'www_subscription_preference', 'www_min_order_value',
               'www_min_order_freeship', 'www_price_break_display', 'delivery_confirmation', 'picking_confirmation',
               'backorder_header_id', ],
    'headers': ['Bu Id', 'Created By', 'Delete Flag', 'Creation Date', 'Last Update Date', 'Record Status',
                'Last Updated By', 'Update Source', 'ID', 'Default Customer', 'Price Type', 'Offer Price Type',
                'Return Sub Location', 'Return Location Id', 'Invoice Report Format', 'Invoice Screen Format',
                'Payment Term', 'Payment Method', 'Default Bank Account', 'GL A/C Code', 'Default Order Type',
                'Cashingup By ', 'Special Offer Hint ', 'Document Path', 'Customer Numbering', 'Barcode Qty Hint',
                'Inventory Requisition Hint', 'Allocate Order Qty', 'Quantity Popup', 'Invoice# Popup',
                'Populate Sales Batch', 'Surcharge A/C Customer', 'Write Invoice To File', 'Central Payment',
                'Print Pay IN/OUT Slip', 'Print Customer Note1', 'Print Customer Note2', 'Print Customer Note3',
                'Apply Offer on Cust Price', 'Output Path', 'Name', 'Preview Mode', 'Batch Mode', 'Execution Mode',
                'Format', 'Copies', 'Name', 'Copies', 'Preview Mode', 'Format', 'Batch Mode', 'Execution Mode',
                'Receipt Printer', '', 'Price Basis ', 'When Credit Limit Reached ',
                'Alert if item sold less then cost +(%)', 'Number of Layaways Allowed Per User', 'Default Item Filter ',
                'Log Off Time Out (Minutes)', 'Must Select a Customer to start a Transaction ',
                'Allow Change of Customer Once Transaction is Started  ', 'Run Back Office Report for Till Receipt ',
                'Log Off After Each Transaction (FO only)', 'Allow Duplicate Customer Name ',
                'Print Sales Batch When Invoice is Finalised  ', 'Allow Minus Stock  ',
                'Allow Part Invoice from Sales Order ', 'Monitor Layaways ', 'Alert Less Then Cost ', 'Mark Up/Down',
                'On', 'Category', 'Subscription', 'Min Order Value', 'Free Ship', 'Show Price Break',
                'Delivery Confirmation', 'Picking Confirmation', 'Default Back Order ID', ],
}
AUDIT_ITEMPRICE_HISTORY = {
    'fields': ['itemprice_history_id', 'item_id', 'supplier_id', 'customer_id', 'location_id', 'sub_location_id',
               'source_object_name', 'source_header_id', 'source_line_id', 'changed_by', 'qty_instock',
               'old_averageprice', 'new_averageprice', 'change_type', 'last_update_date', 'last_updated_by',
               'created_by', 'bu_id', 'delete_flag', 'update_source', 'creation_date', 'transaction_source',
               'change_reason', 'old_price', 'new_price', 'change_category', 'user_name', ],
    'headers': ['Itemprice History Id', 'Item Id', 'Supplier Id', 'Customer Id', 'Location Id', 'Sub Location Id',
                'Source Object Name', 'Source Header Id', 'Source Line Id', 'Changed By', 'Qty Instock',
                'Old Averageprice', 'New Averageprice', 'Change Type', 'Last Update Date', 'Last Updated By',
                'Created By', 'Bu Id', 'Delete Flag', 'Update Source', 'Date', 'Source', 'Reason', 'OLD Price',
                'New Price', 'Category', 'By User', ],
}
CATEGORY_ITEMS = {
    'fields': ['iisc_sub_category_id', 'iic_category_id', 'item_number', 'item_name', 'item_status', 'item_id', ],
    'headers': ['Iisc Sub Category Id', 'Iic Category Id', 'Item Number', 'Item Name', 'Item Status', 'Item Id', ],
}
CMN_BANKS = {
    'fields': ['bu_id', 'creation_date', 'created_by', 'last_updated_by', 'last_update_date', 'record_status',
               'update_source', 'bank_id', 'bank_name', 'debit_amount', 'credit_amount', ],
    'headers': ['Bu Id', 'Creation Date', 'Created By', 'Last Updated By', 'Last Update Date', 'Record Status',
                'Update Source', 'ID', 'Name', 'Debit Amount', 'Credit Amount', ],
}
CMN_BANK_ACCOUNTS = {
    'fields': ['creation_date', 'created_by', 'last_updated_by', 'last_update_date', 'record_status', 'update_source',
               'cb_bank_id', 'gac_gl_account_id', 'bank_account_id', 'branch_code', 'branch_acctnumber',
               'branch_acctname', 'currency_code', 'branch_used_for', 'branch_desc', 'credit_amount', 'debit_amount',
               'branch_allow_payin', 'branch_allow_payout', 'branch_address_line1', 'branch_address_line2',
               'branch_address_line3', 'bank_branch_city', 'bank_branch_county', 'branch_post_code', 'country_code',
               'branch_phone', 'disp_gl_accountcode', ],
    'headers': ['Creation Date', 'Created By', 'Last Updated By', 'Last Update Date', 'Record Status', 'Update Source',
                'Cb Bank Id', 'Gac Gl Account Id', 'ID', 'Code', 'Account Number', 'Account Name', 'Currency Code',
                'Usage Code', 'Description', 'Credit Amount', 'Debit Amount', 'Allow Pay In', 'Allow Pay Out',
                'Address1', '2', '3', 'City', 'County', 'Post Code', 'Country', 'Phone', 'GL A/C ', ],
}
CMN_BUSINESS_UNITS = {
    'fields': ['bu_id', 'bu_inv_footer', 'delete_flag', 'created_by', 'creation_date', 'last_update_date',
               'last_updated_by', 'record_status', 'update_source', 'cc_comp_id', 'bu_name', 'bu_short_name',
               'orig_system_ref_char', 'orig_system_ref_num', 'bu_address_line1', 'bu_city', 'bu_county', 'bu_phone',
               'bu_post_code', 'cco_country_code', 'bu_fax', 'email', 'url', 'gl_account_id', ],
    'headers': ['Bu Id', 'Bu Inv Footer', 'Delete Flag', 'Created By', 'Creation Date', 'Last Update Date',
                'Last Updated By', 'Record Status', 'Update Source', 'Cc Comp Id', 'Name', 'Short Name',
                'Orig Ref Char', 'Orig Ref Num', 'Address', 'City', 'County', 'Phone', 'Post Code', 'Country', 'FAX',
                'Email', 'WEB', 'GL A/C Code', ],
}
CMN_COMMODITY_CODES = {
    'fields': ['last_update_date', 'last_updated_by', 'creation_date', 'created_by', 'bu_id', 'delete_flag',
               'update_source', 'ccc_id', 'commodity_code', 'name', 'section', 'chapter', 'heading', 'active',
               'legal_act', 'exclusions', 'conditions', 'measure_type', 'additional_codes', 'attribute1', 'attribute2',
               'attribute3', 'attribute4', 'attribute5', 'attribute6', 'start_date_active', 'end_date_active',
               'footnote', 'description', ],
    'headers': ['Last Update Date', 'Last Updated By', 'Creation Date', 'Created By', 'Bu Id', 'Delete Flag',
                'Update Source', 'ID', 'Commodity Code', 'Name', 'Section', 'Chapter', 'Heading', 'Active', 'Legal Act',
                'Exclusions', 'Conditions', 'Measure Type', 'Additional Codes', 'Attribute1', 'Attribute2',
                'Attribute3', 'Attribute4', 'Attribute5', 'Attribute6', 'Start Date Active', 'End Date Active',
                'Footnote', 'Description', ],
}
CMN_COMMODITY_RATES = {
    'fields': ['ccc_id', 'attribute1', 'attribute2', 'attribute3', 'attribute4', 'attribute5', 'attribute6',
               'last_update_date', 'last_updated_by', 'creation_date', 'created_by', 'bu_id', 'delete_flag',
               'update_source', 'ccr_id', 'country_code', 'duty_rate', 'start_date_active', 'end_date_active',
               'description', ],
    'headers': ['Ccc Id', 'Attribute1', 'Attribute2', 'Attribute3', 'Attribute4', 'Attribute5', 'Attribute6',
                'Last Update Date', 'Last Updated By', 'Creation Date', 'Created By', 'Bu Id', 'Delete Flag',
                'Update Source', 'ID', 'Country Code', 'Duty Rate', 'Start Date Active', 'End Date Active',
                'Description', ],
}
CMN_COMPANIES = {
    'fields': ['delete_flag', 'creation_date', 'created_by', 'record_status', 'last_update_date', 'last_updated_by',
               'update_source', 'comp_id', 'comp_name', 'comp_trading_name', 'comp_slogan', 'comp_vat_reg_no',
               'comp_reg_no', 'comp_address_line1', 'comp_city', 'comp_county', 'comp_post_code', 'cco_country_code',
               'comp_phone1', 'comp_phone2', 'comp_fax', 'comp_email', 'url', 'orig_system_ref_code',
               'orig_system_ref_desc', 'gl_account_id', 'attribute1', 'attribute2', ],
    'headers': ['Delete Flag', 'Creation Date', 'Created By', 'Record Status', 'Last Update Date', 'Last Updated By',
                'Update Source', 'Comp Id', 'Name', 'Trading Name', 'Tag Line', 'Tax REG No.', 'Registration No.',
                'Address1', 'City', 'County', 'Post Code', 'Country', 'Phone1', 'Phone2', 'FAX', 'email', 'WEB',
                'Orig Sys Ref Code', 'Orig Sys Ref Desc', 'GL A/C Code', 'Comment1', 'Comment2', ],
}
CMN_CONTAINERS = {
    'fields': ['bu_id', 'delete_flag', 'created_by', 'creation_date', 'last_update_date', 'last_updated_by',
               'record_status', 'update_source', 'pc_id', 'pc_code', 'pc_name', 'container_type', 'container_category',
               'container_recycle_code', 'pc_volume', 'pc_max_volume', 'container_type', 'pc_weight', 'pc_max_weight',
               'tare_kg', 'static_load_kg', 'dynamic_load_kg', 'pc_length', 'pc_width', 'pc_height', 'pc_length_mm',
               'pc_width_mm', 'pc_height_mm', 'pc_length_inches', 'pc_width_inches', 'pc_height_inches', ],
    'headers': ['Bu Id', 'Delete Flag', 'Created By', 'Creation Date', 'Last Update Date', 'Last Updated By',
                'Record Status', 'Update Source', 'ID', 'Code', 'Name', 'Type', 'Category', 'Recycle Code',
                'Volume( cubic-cm)', 'Max Volume(cubic - cm)', 'Default Container Type', 'Weight', 'Max Weight', 'Tare',
                'Static Load', 'Dynamic Load', 'Length', 'Width', 'Height', 'Length', 'Width', 'Height', 'Length',
                'Width', 'Height', ],
}
CMN_COUNTRIES = {
    'fields': ['created_by', 'delete_flag', 'creation_date', 'last_update_date', 'last_updated_by', 'record_status',
               'update_source', 'country_code', 'country_name', 'country_region_code', 'language_code', ],
    'headers': ['Created By', 'Delete Flag', 'Creation Date', 'Last Update Date', 'Last Updated By', 'Record Status',
                'Update Source', 'Code', 'Name', 'Region Code', 'Language Code', ],
}
CMN_CURRENCIES = {
    'fields': ['sl_no', 'currency_code', 'currency_name', 'cur_country', 'cur_symbol', 'cur_numeric', 'cur_active',
               'cur_desc', 'cur_triangular_code', 'created_by', 'creation_date', 'bu_id', 'last_update_date',
               'last_updated_by', 'record_status', 'update_source', 'delete_flag', ],
    'headers': ['Sl No', 'Code', 'Name', 'Country', 'Symbol', 'Numeric Value', 'Active', 'Description',
                'Triangular Code', 'Created By', 'Creation Date', 'Bu Id', 'Last Update Date', 'Last Updated By',
                'Record Status', 'Update Source', 'Delete Flag', ],
}
CMN_CURRENCY_RATES = {
    'fields': ['bu_id', 'created_by', 'creation_date', 'last_updated_by', 'last_update_date', 'update_source',
               'delete_flag', 'record_status', 'from_currency_code', 'to_currency_code', 'currency_rate_date',
               'currency_rate', 'sell_currency_rate', 'currency_rate_type', ],
    'headers': ['Bu Id', 'Crated By', 'Creation Date', 'Last Updated By', 'Last Update Date', 'Update Source',
                'Delete Flag', 'Record Status', 'From Currency ', 'To Currency ', 'Date', 'Buying Rate', 'Selling Rate',
                'Type', ],
}
CMN_LANGSOURCES_V = {
    'fields': ['source_object', 'source_object_id', 'source_object_value', ],
    'headers': ['Source Object', 'ID', 'Source Object Value', ],
}
CMN_LANGUAGES = {
    'fields': ['created_by', 'delete_flag', 'creation_date', 'last_update_date', 'last_updated_by', 'record_status',
               'update_source', 'language_code', 'language_name', ],
    'headers': ['Created By', 'Delete Flag', 'Creation Date', 'Last Update Date', 'Last Updated By', 'Record Status',
                'Update Source', 'Code', 'Name', ],
}
CMN_LANGUAGE_TEXTS = {
    'fields': ['last_update_date', 'last_updated_by', 'creation_date', 'created_by', 'bu_id', 'delete_flag',
               'update_source', 'source_object', 'source_object_id', 'language_code', 'source_object_identifier',
               'language_text', 'original_text', ],
    'headers': ['Last Update Date', 'Last Updated By', 'Creation Date', 'Created By', 'Bu Id', 'Delete Flag',
                'Update Source', 'Source Object', 'Source Object Id', 'Language', 'Identifier', 'Language Text',
                'Original Text', ],
}
CMN_LOOKUP_CODES = {
    'fields': ['bu_id', 'delete_flag', 'created_by', 'creation_date', 'last_update_date', 'last_updated_by',
               'record_status', 'update_source', 'clt_lookup_type', 'lookup_code', 'lookup_meaning', 'security_level',
               'sl_no', 'description', 'lookup_default', 'start_date', 'end_date', 'gl_account_id', 'attribute1',
               'attribute2', 'attribute3', 'attribute4', 'attribute5', 'attribute6', 'attribute7', 'attribute8',
               'attribute9', 'attribute10', 'attribute11', 'attribute12', ],
    'headers': ['Bu Id', 'Delete Flag', 'Created By', 'Creation Date', 'Last Update Date', 'Last Updated By',
                'Record Status', 'Update Source', 'Clt Lookup Type', 'Code', 'Short Description', 'Security Level',
                'Sl No', 'Long Description', 'Default', 'Start Date', 'End Date', 'GL A/C Code', 'Attribute1',
                'Attribute2', 'Attribute3', 'Attribute4', 'Attribute5', 'Attribute6', 'Attribute7', 'Attribute8',
                'Attribute9', 'Attribute10', 'Attribute11', 'Attribute12', ],
}
CMN_LOOKUP_TYPES = {
    'fields': ['bu_id', 'delete_flag', 'created_by', 'creation_date', 'last_update_date', 'last_updated_by',
               'record_status', 'update_source', 'lookup_type', 'lookup_module', 'security_level', 'lookup_desc', ],
    'headers': ['Bu Id', 'Delete Flag', 'Created By', 'Creation Date', 'Last Update Date', 'Last Updated By',
                'Record Status', 'Update Source', '', 'Module', 'Security Level', 'Description', ],
}
CMN_MAILMERGE_HEADERS = {
    'fields': ['last_update_date', 'last_updated_by', 'creation_date', 'created_by', 'bu_id', 'delete_flag',
               'update_source', 'merge_header_id', 'merge_type', 'active', 'print_header_image', 'identifier',
               'description', 'merge_owner', 'table_view_name', 'barcode_text', 'sales_unit', 'sl_no', 'report_id',
               'printer_id', ],
    'headers': ['Last Update Date', 'Last Updated By', 'Creation Date', 'Created By', 'Bu Id', 'Delete Flag',
                'Update Source', 'ID', 'Type', 'Active', 'H Image', 'Identifier', 'Description', '', 'Table View Name',
                'Barcode Criteria', 'Sales Unit', 'Sl No', '', '', ],
}
CMN_PAYMENTTERM_BREAKUPS = {
    'fields': ['created_by', 'bu_id', 'delete_flag', 'creation_date', 'last_update_date', 'last_updated_by',
               'record_status', 'update_source', 'cpt_cpt_id', 'cpb_id', 'sl_no', 'cpb_name', 'cpb_percent',
               'cpb_type', ],
    'headers': ['Created By', 'Bu Id', 'Delete Flag', 'Creation Date', 'Last Update Date', 'Last Updated By',
                'Record Status', 'Update Source', 'Cpt Cpt Id', 'ID', 'Sl No', 'Name', 'Percent', 'Type', ],
}
CMN_PAYMENT_METHODS = {
    'fields': ['created_by', 'bu_id', 'delete_flag', 'creation_date', 'last_update_date', 'last_updated_by',
               'record_status', 'update_source', 'gac_gl_account_id', 'out_gl_account_id', 'pmnt_method_id', 'sl_no',
               'pmnt_code', 'pmnt_method', 'gac_gl_account_id', 'out_gl_account_id', 'validation_criteria',
               'pmnt_min_amount', 'pmnt_max_amount', 'pmnt_type', 'charge_type', 'charge_value', 'pay_in', 'pay_out',
               'active', 'cashback_allowed', 'available_to_all', ],
    'headers': ['Created By', 'Bu Id', 'Delete Flag', 'Creation Date', 'Last Update Date', 'Last Updated By',
                'Record Status', 'Update Source', 'Gac Gl Account Id', 'Gac Gl Account Id', 'ID', 'SL#', 'Code',
                'Payment Method', 'Pay inGL A/C ', 'Pay OutGL A/C ',
                'Mandatory Checks (CHECKNUMBER/CARDTYPE/CARDNUM/SECCODE/AUTHCODE/EXPDATE/REFERENCE etc) ', 'Min Amount',
                'Max Amount', 'Payment Type', 'ChargeType', 'Charge Value', 'Pay In', 'Pay Out', 'Active', 'Cashback?',
                'All ?', ],
}
CMN_PAYMENT_TERMS = {
    'fields': ['created_by', 'bu_id', 'delete_flag', 'creation_date', 'last_update_date', 'last_updated_by',
               'record_status', 'update_source', 'cpt_id', 'terms_name', 'terms_days', 'terms_type', ],
    'headers': ['Created By', 'Bu Id', 'Delete Flag', 'Creation Date', 'Last Update Date', 'Last Updated By',
                'Record Status', 'Update Source', 'ID', 'Terms Name', 'Terms Days', 'Terms Type', ],
}
CMN_PERIOD_HEADERS = {
    'fields': ['last_update_date', 'last_updated_by', 'creation_date', 'created_by', 'bu_id', 'delete_flag',
               'update_source', 'attribute1', 'attribute2', 'attribute3', 'attribute4', 'attribute5', 'attribute6',
               'period_header_id', 'period_header_name', 'description', 'module_id', 'active', ],
    'headers': ['Last Update Date', 'Last Updated By', 'Creation Date', 'Created By', 'Bu Id', 'Delete Flag',
                'Update Source', 'Attribute1', 'Attribute2', 'Attribute3', 'Attribute4', 'Attribute5', 'Attribute6',
                'ID', 'Name', 'Description', 'Module', 'Active', ],
}
CMN_PERIOD_LINES = {
    'fields': ['last_update_date', 'last_updated_by', 'creation_date', 'created_by', 'bu_id', 'delete_flag',
               'update_source', 'sl_no', 'period_name', 'actual_date_from', 'actual_date_to', 'period_status',
               'period_status_date', 'active', 'description', 'period_line_id', 'period_month', 'period_year',
               'calendar_date_from', 'calendar_date_to', 'attribute1', 'attribute2', 'attribute3', 'attribute4',
               'attribute5', 'attribute6', 'period_header_id', ],
    'headers': ['Last Update Date', 'Last Updated By', 'Creation Date', 'Created By', 'Bu Id', 'Delete Flag',
                'Update Source', 'Sl No', 'Period Name', 'Actual Date From', 'Actual Date To', 'Period Status',
                'Period Status Date', 'Active', 'Description', ' Line Id', 'Period Month', 'Period Year',
                'Calendar Date From', 'Calendar Date To', 'Attribute1', 'Attribute2', 'Attribute3', 'Attribute4',
                'Attribute5', 'Attribute6', 'Period Header Id', ],
}
CMN_PRICEROUNDINGS = {
    'fields': ['price_rounding_id', 'created_by', 'bu_id', 'delete_flag', 'creation_date', 'last_update_date',
               'last_updated_by', 'record_status', 'update_source', 'from_price', 'to_price', 'round_to', ],
    'headers': ['Price Rounding Id', 'Created By', 'Bu Id', 'Delete Flag', 'Creation Date', 'Last Update Date',
                'Last Updated By', 'Record Status', 'Update Source', 'From Price', 'To Price', 'Round To', ],
}
CMN_REASONS = {
    'fields': ['bu_id', 'delete_flag', 'created_by', 'creation_date', 'last_update_date', 'last_updated_by',
               'record_status', 'update_source', 'reason_code_id', 'reason_name', 'reason_desc', 'gl_account_id', ],
    'headers': ['Bu Id', 'Delete Flag', 'Created By', 'Creation Date', 'Last Update Date', 'Last Updated By',
                'Record Status', 'Update Source', 'ID', 'Reason', 'Description', 'GL A/C Code', ],
}
CMN_SEASONS = {
    'fields': ['bu_id', 'created_by', 'delete_flag', 'creation_date', 'last_update_date', 'last_updated_by',
               'record_status', 'update_source', 'season_code_id', 'season_code', 'season_desc', 'buying_period_from',
               'buying_period_to', 'selling_period_from', 'selling_period_to', 'season_comment', ],
    'headers': ['Bu Id', 'Created By', 'Delete Flag', 'Creation Date', 'Last Update Date', 'Last Updated By',
                'Record Status', 'Update Source', 'ID', 'Name', 'Description', 'Buying Period From', 'Buying Period To',
                'Selling Period From', 'Selling Period To', 'Comment', ],
}
CMN_SYS_OPTIONS = {
    'fields': ['sys_options_id', 'bu_id', 'created_by', 'delete_flag', 'creation_date', 'last_update_date',
               'last_updated_by', 'record_status', 'update_source', 'ver_no', 'financial_year_start_date',
               'currency_code', 'tax_code_id', 'country_code', 'application_directory', 'picture_path',
               'www_image_path', 'company_logo', 'picture_type', 'helpfile', 'helpexec', 'casetype',
               'menu_color_scheme', 'consolidate_item_in_trans', 'enable_notifications', 'batch_format',
               'period_header_id', 'business_type', 'licence_type', 'install_type', 'enable_tparty_interface',
               'enable_emailing', 'smtp_server_name', 'smtp_user_name', 'smtp_password', 'smtp_domain', 'smtp_port',
               'smtp_from_address', 'email_cc', 'email_bcc', 'external_mail_exe', 'report_server_name',
               'report_execution_method', 'report_output_path', 'report_server_url', 'default_browser',
               'back_office_url', 'alternate_report_server', 'alternate_report_url', 'remote_report_url', 'mobile_url',
               'mobile_url_homepage', 'db_string', 'dir_inbound', 'dir_outbound', 'dir_tmp', 'dir_inbound_backup',
               'dir_outbound_backup', ],
    'headers': ['Sys Options Id', 'Bu Id', 'Created By', 'Delete Flag', 'Creation Date', 'Last Update Date',
                'Last Updated By', 'Record Status', 'Update Source', 'Version No', 'Year Start Date', 'Currency Code',
                'Tax Code', 'Country Code', 'Application Directory', 'Picture Path', 'WWW Picture Path', 'Company Logo',
                'Picture Type', 'Help File', 'Help Program', 'CASE Type', 'Menu Color Scheme',
                'Consolidate Item While Transacting ?', 'Enable Notifications ?', 'Batch Format', 'Default Period',
                'Business Type', 'Licence Type', 'Install Type', 'Enable Third Party Interface ?', 'Enable emailing ?',
                'SMTP Server', 'User Name', 'Password', 'SMTP Domain', 'SMTP Port', 'From Address', 'Cc:', 'BCc:',
                'External Exe File', 'Report Server', 'Execution Method', 'Output Path', 'Report Server URL',
                'Default Browser', 'Back Office URL', 'Alternate Report Server', 'Alternate Report Server URL',
                'Remote Report Server URL', 'Mobile URL', 'Mobile URL Home Page', 'DB String', 'In Bound', 'Out Bound',
                'Temp', 'In Bound (Backup)', 'Out  Bound (Backup)', ],
}
CMN_TAX_BREAKUPS = {
    'fields': ['bu_id', 'delete_flag', 'created_by', 'creation_date', 'last_update_date', 'last_updated_by',
               'record_status', 'update_source', 'ctc_tax_code_id', 'ctb_id', 'ctb_name', 'ctb_desc', 'ctb_recoverable',
               'ctb_percent', ],
    'headers': ['Bu Id', 'Delete Flag', 'Created By', 'Creation Date', 'Last Update Date', 'Last Updated By',
                'Record Status', 'Update Source', 'Ctc Tax Code Id', 'ID', 'Name', 'Description', 'Recoverable',
                'Percent', ],
}
CMN_TAX_CODES = {
    'fields': ['tax_code_id', 'tax_code', 'tax_rate', 'tax_desc', 'gac_gl_account_id', 'tax_percent', 'end_date',
               'created_by', 'creation_date', 'delete_flag', 'bu_id', 'last_update_date', 'last_updated_by',
               'record_status', 'update_source', 'gac_gl_account_id', 'tax_print_desc', ],
    'headers': ['ID', 'Code', 'Rate', 'Description', 'GL A/C ', 'Percent', 'End Date', 'Created By', 'Creation Date',
                'Delete Flag', 'Bu Id', 'Last Update Date', 'Last Updated By', 'Record Status', 'Update Source',
                'Gac Gl Account Id', 'Print in Invoice', ],
}
CMN_TERMINALS = {
    'fields': ['created_by', 'creation_date', 'record_status', 'last_update_date', 'last_updated_by', 'update_source',
               'delete_flag', 'terminal_id', 'name', 'bu_id', 'terminal_type', 'hardware_type', 'active', 'print_flag',
               'install_date', 'description', 'hard_disk_volumeno', 'application_directory', ],
    'headers': ['Created By', 'Creation Date', 'Record Status', 'Last Update Date', 'Last Updated By', 'Update Source',
                'Delete Flag', 'ID', 'Name', '', 'Terminal Type', 'Hardware Type', 'Active', 'Print', 'Install Date',
                'Description', 'Hard Disk Volumeno', 'Application Directory', ],
}
CMN_TERMS = {
    'fields': ['bu_id', 'created_by', 'last_update_date', 'last_updated_by', 'record_status', 'creation_date',
               'update_source', 'delete_flag', 'tc_code_id', 'usage', 'sl_no', 'tc_text', 'attribute1', 'attribute2',
               'active', ],
    'headers': ['Bu Id', 'Created By', 'Last Update Date', 'Last Updated By', 'Record Status', 'Creation Date',
                'Update Source', 'Delete Flag', 'ID', 'Usage', 'Sl No', 'Text', 'Attribute1', 'Attribute2', 'Active', ],
}
CMN_UNIT_OF_MEASUREMENTS = {
    'fields': ['bu_id', 'delete_flag', 'created_by', 'creation_date', 'last_update_date', 'last_updated_by',
               'record_status', 'update_source', 'uom_id', 'uom_short_desc', 'uom_long_desc', 'uom_conversion',
               'uom_conversion_desc', 'uom_conv_sdesc', 'uom_printsmalllabel', ],
    'headers': ['Bu Id', 'Delete Flag', 'Created By', 'Creation Date', 'Last Update Date', 'Last Updated By',
                'Record Status', 'Update Source', 'ID', 'UOM', 'Description', 'Conversion Unit', 'Conv Desc',
                'Conv UOM', 'Print', ],
}
DISPATCH_HEADERS = {
    'fields': ['last_update_date', 'last_updated_by', 'creation_date', 'created_by', 'bu_id', 'delete_flag',
               'update_source', 'record_status', 'dispatch_number', 'dispatch_batch', 'veichle_registration',
               'courier_freight_name', 'driver_name', 'notes_to_customer', 'notes_to_driver', 'dispatch_date',
               'dispatch_status', 'dispatch_status_date', 'dispatch_type', 'contact_name', 'description',
               'delivery_address', 'special_notes', 'attribute1', 'attribute2', 'attribute3', 'attribute4',
               'dispatch_id', 'location_id', 'freight_header_id', ],
    'headers': ['Last Update Date', 'Last Updated By', 'Creation Date', 'Created By', 'Bu Id', 'Delete Flag',
                'Update Source', 'Record Status', 'Reference', 'Batch', 'Registration', 'Courier Name', 'Driver Name',
                'Cutomer Notes', 'Driver Notes', 'Date', 'Status', 'Status Date', 'Type', 'Contact Name', 'Description',
                'Deliver Address', 'Special Notes', 'Attribute1', 'Attribute2', 'Attribute3', 'Attribute4', 'ID',
                'Location Id', 'Freight', ],
}
GL_ACCOUNT_CODES = {
    'fields': ['gl_account_id', 'gl_account_code', 'short_name', 'description', 'gl_code_char', 'active',
               'orig_system_ref1', 'orig_system_ref2', 'gl_code_category', 'gl_qualifier_code1', 'gl_qualifier_code2',
               'end_date', 'attribute1_type', 'attribute1', 'attribute2_type', 'attribute2', 'attribute3_type',
               'attribute3', 'attribute4_type', 'attribute4', 'attribute5_type', 'attribute5', 'attribute6_type',
               'attribute6', 'attribute7_type', 'attribute7', 'attribute8_type', 'attribute8', 'attribute9_type',
               'attribute9', 'attribute10_type', 'attribute10', 'attribute11_type', 'attribute11', 'attribute12_type',
               'attribute12', 'bu_id', 'delete_flag', 'created_by', 'creation_date', 'last_update_date',
               'last_updated_by', 'record_status', 'update_source', 'gsc_gl_sub_category_id', 'gc_gl_category_id', ],
    'headers': ['ID', 'A/C Code Num', 'Short Name', 'Description', 'A/C Code Alpha', 'Active', 'Orig Sys Ref1',
                'Orig Sys Ref2', 'Code Type', 'Qualifier 1', 'Qualifier 2', 'End Date', '1', '1', '2', '1', '3', '1',
                '4', '1', '5', '1', '6', '1', '7', '1', '8', '1', '9', '1', '10', '1', '11', '1', '12', '1', 'Bu Id',
                'Delete Flag', 'Created By', 'Creation Date', 'Last Update Date', 'Last Updated By', 'Record Status',
                'Update Source', 'Gsc Gl Sub Category Id', 'Gc Gl Category Id', ],
}
GL_CATEGORIES = {
    'fields': ['gl_category_id', 'gl_category_name', 'gl_qualifier_code1', 'gl_qualifier_code2', 'gl_category_desc',
               'active', 'created_by', 'creation_date', 'last_updated_by', 'last_update_date', 'record_status',
               'delete_flag', 'update_source', 'bu_id', ],
    'headers': ['ID', 'Category Name', 'Qualifier 1', 'Qualifier 2', 'Description', 'Active', 'Created By',
                'Creation Date', 'Last Updated By', 'Last Update Date', 'Record Status', 'Delete Flag', 'Update Source',
                'Bu Id', ],
}
INV_BARCODE_REPOSITORY = {
    'fields': ['last_update_date', 'last_updated_by', 'creation_date', 'created_by', 'bu_id', 'delete_flag',
               'update_source', 'repository_id', 'barcode', 'barcode_status', 'barcode_type', 'active',
               'barcode_description', 'attribute1', 'attribute2', 'attribute3', 'attribute4', 'item_id', 'su_id', ],
    'headers': ['Last Update Date', 'Last Updated By', 'Creation Date', 'Created By', 'Bu Id', 'Delete Flag',
                'Update Source', 'ID', 'Barcode', 'Status', 'Type', 'Active', 'Description', 'Attribute1', 'Attribute2',
                'Attribute3', 'Attribute4', 'Item Id', 'Su Id', ],
}
INV_ITEM_ADJUSTMENTS = {
    'fields': ['location_name', 'sub_location_name', 'report_date', 'batch_name', 'item_number', 'item_name',
               'qty_adjusted', 'reason_desc', 'supplier_name', 'category_name', 'sub_category_name', 'created_by',
               'creation_date', 'daily', 'weekly', 'monthly', 'yearly', 'hourly', 'dailychar', 'weeklychar',
               'monthlychar', 'yearlychar', 'hourlychar', 'bu_id', 'location_id', 'item_id', 'supplier_id',
               'sub_location_id', 'category_id', 'sub_category_id', 'adjust_header_id', 'adjust_line_id',
               'operatorname', ],
    'headers': ['Location', 'Sub Location', 'Updated On', 'Group Code', 'Item Number', 'Item Name', 'Adjusted',
                'Reason', 'Supplier Name', 'Category Name', 'Sub Category Name', 'Created By', 'Creation Date', 'Daily',
                'Weekly', 'Monthly', 'Yearly', 'Hourly', 'Dailychar', 'Weeklychar', 'Monthlychar', 'Yearlychar',
                'Hourlychar', 'Bu Id', 'Location Id', 'Item Id', 'Supplier Id', 'Sub Location Id', 'Category Id',
                'Sub Category Id', ' Header Id', ' Line Id', 'OperatorName', ],
}
INV_ITEM_CATEGORIES = {
    'fields': ['last_update_date', 'last_updated_by', 'record_status', 'update_source', 'bu_id', 'delete_flag',
               'created_by', 'creation_date', 'category_id', 'category_name', 'category_code', 'bin_identifier',
               'category_markup', 'take_snapshot', 'key_words', 'picturename', 'amazon_percent', 'ebay_percent',
               'description', 'attribute1', 'attribute2','on_home_page','active','tags','meta_title','picturename1' ],
    'headers': ['Last Update Date', 'Last Updated By', 'Record Status', 'Update Source', 'Bu Id', 'Delete Flag',
                'Created By', 'Creation Date', 'ID', 'Category', 'Code', 'BIN', 'Markup', 'Snapshot', 'Key Words',
                'Picture Name', 'Amazon %', 'ebay %', 'Description', 'Freetext1', 'Freetext2',
                'On Home Page','Active','Tags','Meta Title','Picture Name' ],
}
INV_ITEM_MASTERS = {
    'fields': ['item_id', 'item_number', 'item_name', 'supplier_product_code', 'inner_qty', 'case_unit', 'pallet_qty',
               'stock_holding_unit', 'min_qty', 'max_qty', 'reorder_qty', 'min_pb_qty', 'alternate_unit_cp',
               'alternate_case_cp', 'unit_cp', 'case_cp', 'short_desc', 'im_manf_id', 'sales_price_flag',
               'ctc_tax_code_id', 'season_code_id', 'ipbh_price_break_id', 'ccc_id', 'item_status', 'qty_available',
               'qty_inorder', 'qty_adjusted', 'qty_allocated', 'qtyinstock', 'qty_sold', 'purchaseable', 'saleable',
               'reservable', 'stockable', 'valuable', 'exchange_rate', 'delivery_charges', 'supplier_unit_cp',
               'supplier_case_cp', 'enforce_reorder_qty', 'reorder_interval', 'reorder_uomid', 'virtual_stock',
               'cmc_pc_id', 'container_weight', 'noof_items_by_weight', 'gross_case_weight', 'net_case_weight',
               'case_length', 'case_width', 'case_height', 'case_volume', 'case_volumetric_weight', 'gross_unit_weight',
               'net_unit_weight', 'unit_length', 'unit_width', 'unit_height', 'unit_volume', 'net_ingredient',
               'unit_volumetric_weight', 'container_volume', 'noof_items_by_volume', 'replenishment_options',
               'customer_notes1', 'customer_notes2', 'customer_notes3', 'supplier_notes1', 'supplier_notes2',
               'item_specifications', 'item_comment', 'key_words', 'technical_specs', 'long_desc',
               'replenished_from_location', 'image_hint', 'picturetype', 'picturename', 'picturename1', 'picturename2',
               'picturename3', 'technical_specs_file', 'demo_video_file', 'serial_numbered', 'print_picture',
               'warrantied', 'weighed_item', 'apply_offer', 'publish_to_web', 'serviceditem', 'track_usage',
               'enforce_tax_code', 'take_snapshot', 'freight', 'freight_price_criteria', 'start_date_active',
               'end_date_active', 'flaginwebexport', 'flagindatefrom', 'flagindateto', 'gac_gl_account_id',
               'sales_gl_account_id', 'costofsales_gl_account_id', 'pricevariance_gl_account_id', 'pnl_gl_account_id',
               'balancesheet_gl_account_id', 'item_style', 'item_colour', 'item_size', 'item_fitting', 'whose_for',
               'www_parent_sku', 'www_relationship_type', 'www_variation_theme', 'www_package_quantity',
               'www_design_pattern', 'www_parentage', 'www_barcode_type', 'group1', 'group2', 'group3', 'group4',
               'warranty_period', 'web_expedite_flag', 'freight_name', 'instrunction', 'opening_balance',
               'closing_balance', 'goodsin_location_id', 'sales_location_id', 'sales_location_qty',
               'last_bought_unitcp', 'average_unitcp', 'trading_unitcp', 'trading_casecp', 'iwc_charge_id',
               'similar_item_id', 'weight_uomid', 'volume_uomid', 'sup_supplier_id', 'iic_category_id',
               'iisc_sub_category_id', 'bu_id', 'delete_flag', 'created_by', 'creation_date', 'last_update_date',
               'last_updated_by', 'record_status', 'item_picture', 'sup_currency_code', 'sup_country_code',
               'item_dimension', 'item_dimension_type', 'item_class_category', 'stock_take_category', 'item_condition',
               'default_label_name', 'mkuptemp_id', 'similar_item_concated', 'uom_id', 'item_prefix', ],
    'headers': ['ID', 'Number', 'Name', 'Supplier Code', 'Inner Qty', 'Case Qty', 'Pallet Qty', 'Stock Holding Unit',
                'Min Qty', 'Max Qty', 'Reorder Qty', 'Min PB Qty', 'USD Unit CP', 'USD Case CP', 'Base Unit CP',
                'Base Case CP', 'Short Name', 'Manf/Brand', 'P Flag:', 'Tax Code', 'Season', 'Price Break',
                'Price Break', 'Item Status', 'Available', 'In Order', 'Adjusted', 'Allocated', 'In Stock', 'Sold',
                'Purchaseable', 'Saleable', 'Reservable', 'Stockable', 'Valuable', 'Xchange Rate',
                'Delivery Charges(Case)', 'FC Unit CP(FOB)', 'FC Case CP(FOB)', 'Enforce Reorder Qty',
                'Reorder Interval(days)', 'Reorder UOM', 'Virtual Stock', 'Name', 'Max Weight', 'No of Items by Weight',
                'GW', 'NW', 'Length', 'Width', 'Height', 'Volume', 'VW', 'GW', 'NW', 'Length', 'Width', 'Height',
                'Volume', 'Net Unit  Ingredient', 'VW', 'Max Volume', 'No, of Items by Volume',
                'Replensihment Criteria', 'Cust Note1', 'Cust Note2', 'Cust Note3', 'Sup Note1', 'Sup Note2',
                'Item Specs', 'Comments', 'Key Words', 'Technical Specs ', 'Long Desc', '', 'Picture Hint',
                'Picture Type', 'Main Picture', 'Picture Name1', 'Picture Name2', 'Picture Name 3',
                'Technical Specs File', 'Demo Video File', 'Serial Numbered', 'Print Picture', 'Warrantied',
                'Weighed Item', 'Apply Offer', 'Publish To Web', 'Serviceditem', 'Track Usage', 'Enforce Tax/Vat Code',
                'Take Snapshot', 'Freight Item', 'Freight Price Criteria', 'Start Date', 'End Date',
                'Flag in Web Export', 'Date from', 'Date To', 'Purchase', 'Sales', 'Cost of Sales', 'Price Variance',
                'P&L', 'Balance Sheet', 'Style', 'Colour', 'Size', 'Fittings', 'Gender / Age', 'Parent SKU',
                'Relationship Type', 'Variation Theme', 'Package Qty', 'Design Pattern', 'Parentage', 'Barcode Type',
                'Group1', 'Group2', 'Group3', 'Group4', 'Warranty Period', 'Expedite Flag', 'Freight Name',
                'Instructions', 'Opening Balance', 'Closing Balance', 'Goodsin Location', 'Sales Location',
                'Sales Location Qty', 'Last Bought UnitCP', 'Average UnitCP', 'Trading UnitCP', 'Trading CaseCP',
                'Weee Charges', 'Similar Item ', 'Weight UOM', 'Volume UOM', 'Supplier', 'Category', 'Sub Category',
                'Bu Id', 'Delete Flag', 'Created By', 'Creation Date', 'Last Update Date', 'Last Updated By',
                'Record Status', '', 'Currency', 'Country', 'Additional Dimensions ?', 'Dimension Type',
                'Class Category', 'Stock Take Category', 'Item Condition', 'Default Label', '', '', ' UOM', '', ],
}
INV_ITEM_MOVEMENT_HEADERS = {
    'fields': ['created_by', 'bu_id', 'creation_date', 'last_updated_by', 'record_status', 'last_update_date',
               'item_movement_header_id', 'update_source', 'delete_flag', 'batch_name', 'movement_type',
               'transfered_on', 'from_location_id', 'from_sub_location_id', 'sourced_from', 'source_ref_no',
               'to_location_id', 'to_sub_location_id', 'issued_to', 'issue_ref_no', 'attribute1',
               'header_movement_status_date', 'item_movement_category', 'header_movement_status', ],
    'headers': ['Created By', 'Bu Id', 'Creation Date', 'Last Updated By', 'Record Status', 'Last Update Date',
                'Item Movement Header Id', 'Update Source', 'Delete Flag', 'Batch', ' Type', 'Date', 'From Location',
                'From Sub Location', 'Source ', ' Reference', 'To Location', 'To Sub Location', 'Issued To',
                'Issue Ref No', 'Notes', 'Status Date', 'Category', 'Status', ],
}
INV_ITEM_MOVEMENT_LINES = {
    'fields': ['to_location_id', 'to_sub_location_id', 'item_movement_line_id', 'iimh_item_movement_header_id',
               'created_by', 'bu_id', 'creation_date', 'last_updated_by', 'record_status', 'last_update_date',
               'update_source', 'delete_flag', 'iim_item_id', 'item_number', 'item_name', 'qty_instock',
               'qty_inlocation', 'quantity', 'sub_location_id', 'qty_goodsin', 'qty_rejected', 'total_grned',
               'reason_for_rejection', 'rejection_sub_location', 'rejection_sub_location_id', 'notes',
               'notes_destination', 'reason_code_id', ],
    'headers': ['To Location', 'To Sub Location', 'Item Movment Line Id', 'Iimh Item Movement Header Id', 'Created By',
                'Bu Id', 'Creation Date', 'Last Updated By', 'Record Status', 'Last Update Date', 'Update Source',
                'Delete Flag', 'Iim Item Id', 'Item Number', 'Item Name', 'Total Location  Stock', 'Qty inStock',
                'Qty TransferTo Location', 'To Sub Location', 'QtyGoodsIn', 'QtyRejected', 'TotalGRNed',
                'RejectionReason', 'Rejection Sub Location', 'To Sub Location', 'Notes (Source)', 'Notes Destination',
                'Reason', ],
}
INV_ITEM_PICKLIST = {
    'fields': ['picklist_id', 'source_header_id', 'source_line_id', 'transaction_source', 'location_id',
               'update_source', 'record_status', 'last_update_date', 'last_updated_by', 'bu_id', 'delete_flag',
               'created_by', 'item_id', 'creation_date', 'sub_location_id', 'quantity', 'picklist_status',
               'picklist_status_date', 'comments', ],
    'headers': ['Picklist Id', 'Order Header Id', 'Order Line Id', 'Transaction Source', 'Location Id', 'Update Source',
                'Record Status', 'Last Update Date', 'Last Updated By', 'Bu Id', 'Delete Flag', 'Created By', '',
                'Creation Date', 'Sub Location Id', 'Quantity', 'Status', 'Status Date', 'Comments', ],
}
INV_ITEM_SUB_CATEGORIES = {
    'fields': ['bu_id', 'delete_flag', 'created_by', 'creation_date', 'record_status', 'last_update_date',
               'last_updated_by', 'update_source', 'iic_category_id', 'sub_category_id', 'sub_category_name',
               'sub_category_code', 'bin_identifier', 'sub_category_markup', 'take_snapshot', 'key_words',
               'picturename', 'amazon_percent', 'ebay_percent', 'description', 'attribute1', 'attribute2', ],
    'headers': ['Bu Id', 'Delete Flag', 'Created By', 'Creation Date', 'Record Status', 'Last Update Date',
                'Last Updated By', 'Update Source', 'Iic Category Id', 'ID', 'Sub Category', 'Code', 'BIN', 'Markup',
                'Snapshot', 'Key Words', 'Picture Name', 'Amazon %', 'ebay %', 'Description', 'Freetext1',
                'Freetext2', ],
}
INV_ITEM_TRANS_HISTORY = {
    'fields': ['trans_seq', 'item_id', 'bu_id', 'location_id', 'sub_location_id', 'source_header_id', 'source_line_id',
               'item_name', 'item_number', 'trans_source', 'report_date', 'location_name', 'sub_location_name',
               'resetqty', 'credit_quantity', 'debit_quantity', 'source_type', 'source_info1', 'source_info2', ],
    'headers': ['Trans Seq', 'Item Id', 'Bu Id', 'Location Id', 'Sub Location Id', 'Source Header Id', 'Source Line Id',
                'Item Name', 'Item Number', 'Trans Source', 'Report Date', 'Location Name', 'Sub Location ',
                'ResetQuantity', 'Credit Quantity', 'Debit Quantity', 'Source Type', 'Source Info1', 'Source Info2', ],
}
INV_LOCATIONS = {
    'fields': ['created_by', 'bu_id', 'creation_date', 'delete_flag', 'last_update_date', 'last_updated_by',
               'record_status', 'update_source', 'location_id', 'location_area_code', 'location_name',
               'location_number', 'location_type', 'gl_account_id', 'location_desc', 'orig_system_ref',
               'location_region_code', 'weee_gl_account_id', 'stockable', 'ship_to', 'bill_to', 'active',
               'take_snapshot', 'address', 'city', 'county', 'country_code', 'post_code', 'phone1', 'phone2', 'fax',
               'location_contact', 'email', 'replenish_location_id', 'item_snapshot_schedule_id', 'purge_snapshot_days',
               'item_snapshot_type', 'location_comment', 'currency_code', 'tax_code_id', 'item_sub_location_hint',
               'length', 'width', 'height', 'total_area', 'stockable_area', 'relative_distance', 'sub_loc_separator',
               'noof_levels', ],
    'headers': ['Created By', 'Bu Id', 'Creation Date', 'Delete Flag', 'Last Update Date', 'Last Updated By',
                'Record Status', 'Update Source', 'ID', 'Area Code', 'Name', 'Number', 'Type', 'Account code ',
                'Description', 'External  Location', 'Region', 'WEEE A/C Code', 'Stockable', 'ShipTo', 'Bill To',
                'Active', 'Snapshot', 'Address ', 'City', 'County', 'Country', 'Post Code', 'Phone1', 'Phone2', 'Fax',
                'Contact', 'email', '', 'Schedule', 'Purge Snapshot (days)', 'Snapshot Type', 'Comments', 'Currency',
                'Tax Rate', 'Item Primary Sub Loc Hint', 'Length', 'Width', 'Height', 'Total Area(sq feet)',
                'Stockable Area(sq feet)', 'Relative Distance', 'Sub Loc Separator', 'No of Levels', ],
}
INV_OPTIONS = {
    'fields': ['inv_options_id', 'bu_id', 'created_by', 'delete_flag', 'creation_date', 'last_update_date',
               'last_updated_by', 'record_status', 'update_source', 'stock_search', 'item_order_by', 'item_number',
               'default_markup', 'noof_selling_price', 'stock_adjustment_reason', 'manf_id', 'season_code_id',
               'category_id', 'sub_category_id', 'price_break_id', 'location_id', 'printer_id', 'markup_type',
               'price_check_hint', 'quantity_format', 'populate_stock_history', 'min_qty_formula', 'max_qty_formula',
               'reorder_qty_formula', 'sub_location', 'printer_copies', 'batch_format', 'print_output_path',
               'price_break_criteria', 'report_markup_type', 'primary_sub_location_hint', 'req_rcv_sub_location_hint',
               'uom_id', 'single_uom_id', 'box_uom_id', 'weight_uom_id', 'volume_uom_id', 'dimension_uom_id',
               'volume_divider', 'gl_account_id', 'debit_gl_account_id', 'sales_gl_account_id', 'credit_gl_account_id',
               'costofsales_gl_account_id', 'pricevariance_gl_account_id', 'pnl_gl_account_id',
               'balancesheet_gl_account_id', 'defualt_picture_name', 'maintain_minusstock_separately',
               'prefix_itemnumber', 'add_item_to_location', 'snapshot_all_items', 'ignore_location_attributes',
               'auto_release_to_web', 'export_all_items', 'enable_palleting', ],
    'headers': ['Inv Options Id', 'Bu Id', 'Created By', 'Delete Flag', 'Creation Date', 'Last Update Date',
                'Last Updated By', 'Record Status', 'Update Source', 'Item Search', 'Item Order By', 'Item Numbering',
                ' Default Markup', ' No of Default SP', 'Stock Adjustment Reason', 'Manufacturer', 'Season Code',
                'Category', 'Sub Category', 'Price Break', 'Location ', 'Printer ', 'Markup Type', 'Price Check Hint',
                'Quantity Format', 'Populate Stock  History', 'Min Qty Formula', 'Max Qty Formula',
                'Reorder Qty Formula', 'Sub Location', 'Printer Copies', 'Batch Format', 'Output Path',
                'Price Break Criteria', 'How to Report Profit?', 'Default Item  Sub Location Hint',
                'Requisition  Sub Location Hint', 'Default UOM', 'Single  UOM', 'Box UOM', 'Weight UOM', 'Volume UOM',
                'Dimension UOM', 'Volume Divider', 'Default GL A/C', 'Debit GL  A/C', 'Sales GL  A/C', 'Credit GL A/C ',
                'Cost of Sales GL  A/C', 'Price Variance GL  A/C', 'P&L GL  A/C', 'Balance Sheet GL  A/C',
                'Defualt Picture Name', 'Maintain Minus Qty Separately', 'Prefix Item Number',
                'Add Items to Location(Auto)', 'Snapshot All Items', 'Ignore Location Attributes',
                'Auto Release (When In Stock)', 'Export All Items', 'Enable Palleting', ],
}
INV_PRICE_BREAK_HEADERS = {
    'fields': ['delete_flag', 'created_by', 'creation_date', 'bu_id', 'last_update_date', 'last_updated_by',
               'record_status', 'update_source', 'item_id', 'price_break_id', 'name', 'description',
               'user_display_text', 'date_from', 'date_to', ],
    'headers': ['Delete Flag', 'Created By', 'Creation Date', 'Bu Id', 'Last Update Date', 'Last Updated By',
                'Record Status', 'Update Source', 'Item ID', 'ID', 'Name', 'Description', 'User Text', 'Date From',
                'Date To', ],
}
INV_PRICE_BREAK_LINES = {
    'fields': ['ipbh_price_break_id', 'delete_flag', 'created_by', 'creation_date', 'bu_id', 'last_update_date',
               'last_updated_by', 'record_status', 'update_source', 'price_break_line_id', 'sl_no', 'sales_unit',
               'price_break_source_type', 'qty_from_source', 'qty_to_source', 'qty_from', 'qty_from_plusminus',
               'qty_to', 'qty_to_plusminus', 'price_break_type', 'price_break_value', 'ipt_price_type_id',
               'user_display_text', ],
    'headers': ['Ipbh Price Break Id', 'Delete Flag', 'Created By', 'Creation Date', 'Bu Id', 'Last Update Date',
                'Last Updated By', 'Record Status', 'Update Source', 'ID', 'Sl No', 'Sales Unit', 'Qty SourceType',
                'Qty From Source', 'Qty ToSource', 'Qty From', 'Qty From +/-', 'Qty To', 'Qty To +/-', 'Type', 'Value',
                'Price Name', 'User Text', ],
}
INV_PRICE_TYPES = {
    'fields': ['last_update_date', 'last_updated_by', 'record_status', 'update_source', 'bu_id', 'delete_flag',
               'created_by', 'creation_date', 'sl_no', 'price_type_id', 'price_type_name', 'min_unit', 'price_inctax',
               'price_exltax', 'price_markup', 'currency_code', 'price_type_group_code', 'description', ],
    'headers': ['Last Update Date', 'Last Updated By', 'Record Status', 'Update Source', 'Bu Id', 'Delete Flag',
                'Created By', 'Creation Date', 'Sl No', 'ID', 'Name', 'Sales Unit', 'Price Inctax', 'Price Exltax',
                'Markup', 'Currency', 'Group Code', 'Description', ],
}
INV_REQUISITION_HEADERS = {
    'fields': ['priority_code', 'requisition_status', 'requisition_status_date', 'last_update_date', 'last_updated_by',
               'creation_date', 'created_by', 'picked_by', 'fulfilled_by', 'received_by', 'cancelled_by', 'bu_id',
               'delete_flag', 'update_source', 'requisition_number', 'requested_by', 'ammended_by', 'requisition_date',
               'picked_date', 'fulfilled_date', 'received_date', 'requisition_phase_code', 'from_location_id',
               'to_location_id', 'batch_name', 'requisition_name', 'requisition_type', 'requisition_category',
               'requisition_source', 'description', 'need_by_date', 'requisition_id', 'start_date_active',
               'end_date_active', 'active', ],
    'headers': ['Priority', 'Status', 'Status Date', 'Last Update Date', 'Last Updated By', 'Creation Date',
                'Created By', 'Created By', 'Created By', 'Created By', 'Created By', 'Bu Id', 'Delete Flag',
                'Update Source', 'REQUISITION #', 'Requested By', 'Ammended  By', 'On ', 'On ', 'On ', 'On ',
                'Phase Code', 'From Location ID', 'To Location ID', 'Batch', 'Name', ' Type', 'Category', 'Source',
                'Notes', 'Need By', 'ID', 'Start Date', 'End Date', 'Active', ],
}
INV_REQUISITION_LINES = {
    'fields': ['requisition_id', 'picked_location_id', 'picked_sub_location_id', 'item_id', 'last_update_date',
               'last_updated_by', 'creation_date', 'created_by', 'bu_id', 'delete_flag', 'update_source', 'sl_no',
               'qty_requested_units', 'qty_allocated_units', 'qty_fullfilled_units', 'qty_received_units',
               'qty_difference_units', 'qty_balance_units', 'case_size', 'hint', 'need_by_date', 'priority_code',
               'description', 'notes1', 'requisition_line_id', 'requisition_line_status',
               'requisition_line_status_date', 'qty_instock', 'qty_inorder', 'qty_allocated', 'qty_reserved',
               'qty_goodsin', 'qty_sold', 'qty_reserved_fulfilled', 'qty_reserved_balance', 'qty_reserved_po',
               'qty_reserved_grn', 'qty_reserved_invoiced', 'last_sold_date', 'last_bought_date', 'enforce_reorder_qty',
               'received_sub_location_id', 'picturename', 'picturetype', ],
    'headers': ['Requisition Id', 'Picked Location Id', 'Picked Sub Location Id', 'Item Id', 'Last Update Date',
                'Last Updated By', 'Creation Date', 'Created By', 'Bu Id', 'Delete Flag', 'Update Source', 'Sl No',
                'RequisitionQuantity', 'AllocatedQuantity', 'FullfilledQuantity', 'ReceivedQuantity',
                'DifferenceQuantity', 'BalanceQuantity', 'Case Qty', '', 'Need By Date', 'Priority Code', 'Description',
                'Notes1', 'ID', 'Line Status', 'Status Date', '', '', 'Requested From Stock', 'In Order', 'Allocated',
                'Reserved', 'GRN', 'Sold', 'ResFulfilled', 'ResBalance', 'ResPO', 'ResGRN', 'ResINV', 'Last Sold',
                'Last Bought', 'Enforce Reorder Qty', '', '', '', ],
}
INV_SUB_LOCATIONS = {
    'fields': ['created_by', 'bu_id', 'creation_date', 'delete_flag', 'last_update_date', 'last_updated_by',
               'record_status', 'update_source', 'il_location_id', 'sub_location_id', 'pallet_header_id',
               'sub_location', 'sub_location_number', 'sub_location_type', 'sub_loc_group_code', 'primary', 'active',
               'stocktake', 'stockable', 'valuable', 'include_stock', 'take_snapshot', 'pickable', 'adjustable',
               'short_name', 'min_qty', 'noof_units', 'max_qty', 'length', 'width', 'height', 'total_area',
               'stockable_area', 'aisle', 'bin', 'relative_distance', 'storage_area1', 'storage_area2', 'storage_area3',
               'description', 'gl_account_id', 'level0_hierarchy', 'hierarchy1', 'hierarchy2', 'hierarchy3',
               'hierarchy4', 'hierarchy5', 'hierarchy6', 'hierarchy7', 'hierarchy8', 'hierarchy9', 'hierarchy10', ],
    'headers': ['Created By', 'Bu Id', 'Creation Date', 'Delete Flag', 'Last Update Date', 'Last Updated By',
                'Record Status', 'Update Source', 'Il Location Id', 'ID', 'ID', 'Sub Location', 'Number', 'Type',
                'Group Code ', 'Primary ?', 'Active', 'Auto StkTake?', 'Stock ?', 'Valuable?', 'Include?', 'Snapshot',
                'Pick?', 'Adj?', 'Short Name', 'MINQty', 'AVGQty', 'MAXQty', 'Length(feet)', 'Width(feet)',
                'Height(feet)', 'Total  Area(sq feet)', 'StockableArea(sq feet)', 'Row', 'Locator', 'RelativeDistance',
                'Storage Type 1', 'Storage Type 2', 'Storage Type 3', 'Description', 'Account code ', 'Level0',
                'Hierarchy1', 'Hierarchy2', 'Hierarchy3', 'Hierarchy4', 'Hierarchy5', 'Hierarchy6', 'Hierarchy7',
                'Hierarchy8', 'Hierarchy9', 'Hierarchy10', ],
}
PALLETS_IN_DISPATCH = {
    'fields': ['pallet_header_id', 'pallet_date', 'pallet_type', 'pallet_source', 'pallet_destination', 'pallet_tag',
               'pallet_decription', 'active', 'pallet_age', 'pallet_header_status_date', 'location_id',
               'sub_location_id', 'current_sub_location_id', 'current_location_id', 'order_header_id',
               'invoice_header_id', 'grn_id', 'pc_id', 'source_ref_id1', 'ext_ref_id1', 'ext_ref_id2', 'ext_ref_id3',
               'attribute1', 'attribute2', 'attribute3', 'attribute4', 'no_of_units', 'unit_desc', 'pallet_weight',
               'pallet_length', 'pallet_width', 'pallet_height', 'pallet_volume', 'last_update_date', 'last_updated_by',
               'creation_date', 'pallet_name', 'created_by', 'bu_id', 'delete_flag', 'update_source', 'record_status',
               'source_object_ref', 'source_ref_id2', 'sl_no', 'pallet_number', 'customer_name', 'pallet_header_status',
               'dispatch_id', ],
    'headers': ['Pallet Header Id', 'Pallet Date', 'Pallet Type', 'Pallet Source', 'Pallet Destination', 'Pallet Tag',
                'Pallet Decription', 'Active', 'Pallet Age', 'Pallet Header Status Date', 'Location Id',
                'Sub Location Id', 'Current Sub Location Id', 'Current Location Id', 'Order Header Id',
                'Invoice Header Id', 'Grn Id', 'Pc Id', 'Source Ref Id1', 'Ext Ref Id1', 'Ext Ref Id2', 'Ext Ref Id3',
                'Attribute1', 'Attribute2', 'Attribute3', 'Attribute4', 'No Of Units', 'Unit Desc', 'Pallet Weight',
                'Pallet Length', 'Pallet Width', 'Pallet Height', 'Pallet Volume', 'Last Update Date',
                'Last Updated By', 'Creation Date', '', 'Created By', 'Bu Id', 'Delete Flag', 'Update Source',
                'Record Status', 'Source', 'Source Ref', 'Sl No', 'Pallet Number', 'Deliver  To/From', 'Status', '', ],
}
REP_INTRASTATE_V = {
    'fields': ['shipto_address', 'bu_id', 'invoice_date', 'created_by', 'creation_date', 'last_updated_by',
               'last_update_date', 'delivered_by', 'delivered_date', 'customer_signature_date', 'customer_signature_by',
               'transaction_phase_code', 'marketing_source_code', 'packing_instructions', 'shipping_instructions',
               'drop_ship_flag', 'invoice_category_code', 'ar_return_reason_code', 'salcr_group_id', 'sales_person_id',
               'emp_id', 'attribute6', 'attribute5', 'attribute4', 'attribute3', 'attribute2', 'attribute1',
               'deliverto_contact_id', 'deliverto_customer_id', 'invoiceto_contact_id', 'invoiceto_customer_id',
               'shipfrom_location_id', 'payto_location_id', 'freight_terms_code', 'freight_carrier_code',
               'shipping_method_code', 'partial_shipments_allowed', 'tax_exempt_reason_code', 'tax_exempt_number',
               'tax_exempt_flag', 'pricing_date', 'pricelist_header_id', 'invoice_source', 'period_line_id',
               'period_name', 'gl_accounting_date', 'invoice_header_id', 'invoice_status', 'gl_account_id',
               'pmnt_method_id', 'cpt_id', 'description', 'notes2', 'notes1', 'batch_name', 'invoice_type',
               'carriage_total', 'discount_total', 'balance_total', 'gross_total', 'vat_total', 'net_total',
               'payment_currency_code', 'invoice_currency_code', 'customer_id', 'update_source', 'delete_flag',
               'cancelled_amount', 'cancelled_by', 'cancelled_date', 'authorized_by', 'exchange_rate', 'promised_date',
               'needby_date', 'customer_po_date', 'customer_po_number', 'invoice_user_id', 'order_header_id',
               'discount_value', 'discount_type', 'freight_header_id', 'freight_rate', 'freight_qty', 'freight_line_id',
               'end_release_date', 'start_release_date', 'last_release_date', 'release_schedule_id',
               'orig_sys_ref_header', 'ingredient_total', 'volume_total', 'weight_total', 'billto_address',
               'credit_invoice_header_id', 'terminal_id', 'paid_amount', 'total_cost', 'invbatch_group_id',
               'delivery_freetext', 'number_of_boxes', 'additional_amount', 'grand_total', 'one_off_customer',
               'item_id', 'gross_unit_weight', 'unit_volume', 'billto_address_line1', 'billto_city', 'billto_county',
               'billto_post_code', 'sl_no', 'invoice_line_id', 'commodity_code', 'item_number', 'item_name',
               'qty_invoiced_units', 'net_total_after_discount', 'netweight', 'netvolume', 'country_region_code',
               'invoice_number', 'invoice_status_date', 'billto_country_code', 'customer_name', ],
    'headers': ['Shipto Address', 'Bu Id', 'Invoice Date', 'Created By', 'Creation Date', 'Last Updated By',
                'Last Update Date', 'Delivered By', 'Delivered Date', 'Customer Signature Date',
                'Customer Signature By', 'Transaction Phase Code', 'Marketing Source Code', 'Packing Instructions',
                'Shipping Instructions', 'Drop Ship Flag', 'Invoice Category Code', 'Ar Return Reason Code',
                'Salcr Group Id', 'Sales Person Id', 'Emp Id', 'Attribute6', 'Attribute5', 'Attribute4', 'Attribute3',
                'Attribute2', 'Attribute1', 'Deliverto Contact Id', 'Deliverto Customer Id', 'Invoiceto Contact Id',
                'Invoiceto Customer Id', 'Shipfrom Location Id', 'Payto Location Id', 'Freight Terms Code',
                'Freight Carrier Code', 'Shipping Method Code', 'Partial Shipments Allowed', 'Tax Exempt Reason Code',
                'Tax Exempt Number', 'Tax Exempt Flag', 'Pricing Date', 'Pricelist Header Id', 'Invoice Source',
                'Period Line Id', 'Period Name', 'Gl Accounting Date', 'Invoice Header Id', 'Invoice Status',
                'Gl Account Id', 'Pmnt Method Id', 'Cpt Id', 'Description', 'Notes2', 'Notes1', 'Batch Name',
                'Invoice Type', 'Carriage Total', 'Discount Total', 'Balance Total', 'Gross Total', 'Vat Total',
                'Net Total', 'Payment Currency Code', 'Invoice Currency Code', 'Customer Id', 'Update Source',
                'Delete Flag', 'Cancelled Amount', 'Cancelled By', 'Cancelled Date', 'Authorized By', 'Exchange Rate',
                'Promised Date', 'Needby Date', 'Customer Po Date', 'Customer Po Number', 'Invoice User Id',
                'Order Header Id', 'Discount Value', 'Discount Type', 'Freight Header Id', 'Freight Rate',
                'Freight Qty', 'Freight Line Id', 'End Release Date', 'Start Release Date', 'Last Release Date',
                'Release Schedule Id', 'Orig Sys Ref Header', 'Ingredient Total', 'Volume Total', 'Weight Total',
                'Billto Address', 'Credit Invoice Header Id', 'Terminal Id', 'Paid Amount', 'Total Cost',
                'Invbatch Group Id', 'Delivery Freetext', 'Number Of Boxes', 'Additional Amount', 'Grand Total',
                'One Off Customer', 'Item Id', 'Gross Unit Weight', 'Unit Volume', 'Billto Address Line1',
                'Billto City', 'Billto County', 'Billto Post Code', 'Sl No', 'Invoice Line Id', 'Commodity Code',
                'Item Number', 'Item Name', 'Qty Invoiced', 'Net Total ', 'Net Weight', 'Net Volume', 'Region Code',
                'Invoice Number', 'Invoice Date', 'Country', 'Customer Name', ],
}
REP_ITEMSTATUS_QUERY = {
    'fields': ['item_number', 'item_name', 'supplier_name', 'category_name', 'sub_category_name', 'item_status',
               'min_qty', 'max_qty', 'qty_inorder', 'last_grn_qty', 'last_po_qty', 'last_sold_qty',
               'days_since_last_sold', 'days_since_po', 'days_since_last_bought', 'days_since_created', 'lead_time',
               'safety_net_days', 'typical_daily_usage_stat', 'min_qty_suggested', 'max_qty_suggested',
               'min_max_cal_type_stat', 'qty_sold', 'sal_week1', 'sal_week2', 'sal_week3', 'sal_week4', 'sal_week5',
               'sal_week6', 'six_week_sales', 'avg_week_sales', 'sal_lastmonth', 'sal_jan', 'sal_feb', 'sal_mar',
               'sal_apr', 'sal_may', 'sal_jun', 'jan_jun_sales', 'avg_jan_jun_sales', 'sal_jul', 'sal_aug', 'sal_sep',
               'sal_oct', 'sal_nov', 'sal_dec', 'jul_dec_sales', 'avg_jul_dec_sales', 'sal_ytd', 'created_by',
               'creation_date', 'last_adjust_date', 'last_sold_date', 'last_bought_date', 'last_po_date', 'bu_id',
               'item_id', 'sup_supplier_id', 'iic_category_id', 'iisc_sub_category_id', 'group_stock', 'case_cp',
               'unit_cp', 'case_unit', 'stock_value', 'stockable', 'valuable', 'virtual_stock', 'supplier_number',
               'order_cycle_type', 'order_cycle', 'manufacturer', 'season', 'qty_returned_to_supplier',
               'qty_returned_from_customer', 'qty_adjusted', 'qty_goodsin', 'qty_reserved', 'qty_allocated',
               'qty_instock', 'qty_reserved_invoiced', 'qty_reserved_grn', 'qty_reserved_po', 'qty_reserved_balance',
               'qty_reserved_fulfilled', 'iwc_charge_id', 'update_source', 'ipbh_price_break_id', 'pallet_qty',
               'item_comment', 'item_specifications', 'supplier_notes3', 'supplier_notes2', 'supplier_notes1',
               'customer_notes3', 'customer_notes2', 'customer_notes1', 'item_style', 'item_fitting', 'item_size',
               'item_colour', 'goodsin_location_id', 'sales_location_id', 'gross_unit_weight', 'gross_case_weight',
               'gac_gl_account_id', 'cmc_pc_id', 'im_manf_id', 'ctc_tax_code_id', 'warranty_period', 'group4', 'group3',
               'group2', 'group1', 'whose_for', 'sales_location_qty', 'reservable', 'net_ingredient', 'flagindateto',
               'flagindatefrom', 'flaginwebexport', 'print_picture', 'net_case_weight', 'net_unit_weight', 'warrantied',
               'serial_numbered', 'serviceditem', 'saleable', 'purchaseable', 'volume_uomid', 'weight_uomid',
               'unit_volume', 'unit_height', 'unit_width', 'unit_length', 'case_volume', 'case_height', 'case_width',
               'case_length', 'similar_item_id', 'weighed_item', 'alternate_unit_cp', 'alternate_case_cp', 'qtyinstock',
               'short_desc', 'opening_balance', 'record_status', 'last_updated_by', 'last_update_date', 'track_usage',
               'supplier_product_code', 'picturetype', 'picturename', 'season_code_id', 'closing_balance',
               'delete_flag', 'long_desc', 'stock_holding_unit', 'reorder_uomid', 'reorder_qty', 'reorder_interval',
               'stock_take_category', 'item_class_category', 'item_dimension_type', 'item_dimension', 'trading_casecp',
               'trading_unitcp', 'average_unitcp', 'last_bought_unitcp', 'end_date_active', 'start_date_active',
               'balancesheet_gl_account_id', 'pnl_gl_account_id', 'pricevariance_gl_account_id',
               'costofsales_gl_account_id', 'sales_gl_account_id', 'inner_qty', 'freight', 'take_snapshot',
               'demo_video_file', 'similar_item_concated', 'enforce_tax_code', 'apply_offer', 'picturename3',
               'picturename2', 'picturename1', 'technical_specs_file', 'technical_specs', 'freight_price_criteria',
               'enforce_reorder_qty', 'external_reference', 'ccc_id', 'delivery_charges', 'supplier_unit_cp',
               'supplier_case_cp', 'min_pb_qty', 'mkuptemp_id', 'publish_to_web', 'default_label_name',
               'replenishment_options', 'replenished_from_location', 'key_words', 'exchange_rate', 'image_hint',
               'instrunction', 'item_condition', 'stp_id', 'stp_level1_id', 'stp_level2_id', 'stp_level3_id',
               'stp_level4_id', 'stp_level5_id', 'stp_level6_id', 'unit_volumetric_weight', 'case_volumetric_weight',
               'web_expedite_flag', 'www_parent_sku', 'www_relationship_type', 'www_variation_theme',
               'www_package_quantity', 'www_design_pattern', 'www_parentage', 'www_barcode_type', 'freight_line_id',
               'freight_name', ],
    'headers': ['Item Number', 'Item Name', 'Supplier Name', 'Category Name', 'Sub Category Name', 'Item Status',
                'Min Qty', 'Max Qty', 'Qty Inorder', 'Last Grn Qty', 'Last Po Qty', 'Last Sold Qty', 'DaysSince Sold',
                'DaysSince PO', 'DaysSince GRN', 'DaysSince Created', 'Lead Time', 'SafetyNet', 'DailyUsage',
                'SuggestedMIN', 'SuggestedMAX', 'CurrentMAX', 'Qty Sold', 'Week1', 'Week2', 'Week3', 'Week4', 'Week5',
                'Week6', 'Six Week', 'Avg Weekly', 'Last Month', 'JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN',
                'JAN -JUN SALE', 'Avg JAN -JUN SALES', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC', 'JUL -DEC SALE',
                'Avg JUL -DEC SALES', 'Year to date', 'Created By', 'Creation Date', 'Last Adjust Date',
                'Last Sold Date', 'Last Bought Date', 'Last Po Date', 'Bu Id', 'Item Id', 'Supplier Id', 'Category Id',
                'Sub Category Id', 'In Stock', 'Case Cp', 'Unit Cp', 'Case Unit', 'Stock Value', 'STK', 'VAL',
                'Virtual Stock', 'Supplier Number', 'Order Cycle Type', 'Order Cycle', 'Manufacturer', 'Season',
                'Qty Returned To Supplier', 'Qty Returned From Customer', 'Qty Adjusted', 'Qty Goodsin', 'Qty Reserved',
                'Qty Allocated', 'Qty Instock', 'Qty Reserved Invoiced', 'Qty Reserved Grn', 'Qty Reserved Po',
                'Qty Reserved Balance', 'Qty Reserved Fulfilled', 'Iwc Charge Id', 'Update Source',
                'Ipbh Price Break Id', 'Pallet Qty', 'Item Comment', 'Item Specifications', 'Supplier Notes3',
                'Supplier Notes2', 'Supplier Notes1', 'Customer Notes3', 'Customer Notes2', 'Customer Notes1',
                'Item Style', 'Item Fitting', 'Item Size', 'Item Colour', 'Goodsin Location Id', 'Sales Location Id',
                'Gross Unit Weight', 'Gross Case Weight', 'Gac Gl Account Id', 'Cmc Pc Id', 'Im Manf Id',
                'Ctc Tax Code Id', 'Warranty Period', 'Group4', 'Group3', 'Group2', 'Group1', 'Whose For',
                'Sales Location Qty', 'Reservable', 'Net Ingredient', 'Flagindateto', 'Flagindatefrom',
                'Flaginwebexport', 'Print Picture', 'Net Case Weight', 'Net Unit Weight', 'Warrantied',
                'Serial Numbered', 'Serviceditem', 'Saleable', 'Purchaseable', 'Volume Uomid', 'Weight Uomid',
                'Unit Volume', 'Unit Height', 'Unit Width', 'Unit Length', 'Case Volume', 'Case Height', 'Case Width',
                'Case Length', 'Similar Item Id', 'Weighed Item', 'Alternate Unit Cp', 'Alternate Case Cp',
                'Qtyinstock', 'Short Desc', 'Opening Balance', 'Record Status', 'Last Updated By', 'Last Update Date',
                'Track Usage', 'Supplier Product Code', 'Picturetype', 'Picturename', 'Season Code Id',
                'Closing Balance', 'Delete Flag', 'Long Desc', 'Stock Holding Unit', 'Reorder Uomid', 'Reorder Qty',
                'Reorder Interval', 'Stock Take Category', 'Item Class Category', 'Item Dimension Type',
                'Item Dimension', 'Trading Casecp', 'Trading Unitcp', 'Average Unitcp', 'Last Bought Unitcp',
                'End Date Active', 'Start Date Active', 'Balancesheet Gl Account Id', 'Pnl Gl Account Id',
                'Pricevariance Gl Account Id', 'Costofsales Gl Account Id', 'Sales Gl Account Id', 'Inner Qty',
                'Freight', 'Take Snapshot', 'Demo Video File', 'Similar Item Concated', 'Enforce Tax Code',
                'Apply Offer', 'Picturename3', 'Picturename2', 'Picturename1', 'Technical Specs File',
                'Technical Specs', 'Freight Price Criteria', 'Enforce Reorder Qty', 'External Reference', 'Ccc Id',
                'Delivery Charges', 'Supplier Unit Cp', 'Supplier Case Cp', 'Min Pb Qty', 'Mkuptemp Id',
                'Publish To Web', 'Default Label Name', 'Replenishment Options', 'Replenished From Location',
                'Key Words', 'Exchange Rate', 'Image Hint', 'Instrunction', 'Item Condition', 'Stp Id', 'Stp Level1 Id',
                'Stp Level2 Id', 'Stp Level3 Id', 'Stp Level4 Id', 'Stp Level5 Id', 'Stp Level6 Id',
                'Unit Volumetric Weight', 'Case Volumetric Weight', 'Web Expedite Flag', 'Www Parent Sku',
                'Www Relationship Type', 'Www Variation Theme', 'Www Package Quantity', 'Www Design Pattern',
                'Www Parentage', 'Www Barcode Type', 'Freight Line Id', 'Freight Name', ],
}
REP_SAGETRANSEXPORT_V = {
    'fields': ['trans_id', 'trans_type', 'report_date', 'account_ref', 'gl_code', 'net_amount', 'tax_amount',
               'exchange_rate', 'trans_reference', 'payment_method', 'operatorname', 'account_name', 'trans_source',
               'extra_reference', ],
    'headers': ['Trans_Id', 'Sage Type', 'Date', 'AccountNumber', 'GL Code', 'Net Amount', 'Tax Amount ', 'XchangeRate',
                'Reference', 'Payment Method', 'User', 'Account Name', 'Source', 'Extra Reference', ],
}
REP_STKTAKEAUDIT_V = {
    'fields': ['location_name', 'sub_location_name', 'report_date', 'stktake_name', 'item_number', 'item_name',
               'qty_instock', 'qty_counted', 'diffqty', 'percentagediff', 'batch_name', 'comments', 'supplier_name',
               'category_name', 'sub_category_name', 'reason_name', 'reason_desc', 'stktake_type', 'created_by',
               'creation_date', 'daily', 'weekly', 'count_date', 'monthly', 'yearly', 'hourly', 'dailychar',
               'weeklychar', 'monthlychar', 'yearlychar', 'hourlychar', 'item_count_header_id', 'bu_id', 'location_id',
               'item_id', 'ctc_tax_code_id', 'supplier_id', 'item_count_line_id', 'sub_location_id', 'stktake_type_id',
               'reason_code_id', 'operatorname', 'averagevalue', 'lastboughtvalue', 'basevalue', 'unit_cp',
               'average_unitcp', 'last_bought_unitcp', 'count_status', 'stockable', 'valuable', 'minus_quantity', ],
    'headers': ['Location', 'Sub Location', 'Approved On', 'Stock Take', 'Item Number', 'Item Name', 'Qty Instock',
                'Qty Counted', 'QtyDifference', '%Difference', 'Batch Name', 'Comments', 'Supplier Name',
                'Category Name', 'Sub Category Name', 'Reason Name', 'Reason Desc', 'Stktake Type', 'Created By',
                'Creation Date', 'Daily', 'Weekly', 'Count Date', 'Monthly', 'Yearly', 'Hourly', 'Dailychar',
                'Weeklychar', 'Monthlychar', 'Yearlychar', 'Hourlychar', 'ID', 'Bu Id', 'Location Id', 'Item Id',
                'Tax Code Id', 'Supplier Id', ' Line Id', 'Sub Location Id', 'Stktake Type Id', 'Reason Code Id',
                'OperatorName', 'Average Value', ' Last Bought Value', 'Base Value', 'Unit CP', 'Average Unit CP',
                'Last BoughtUnit CP', ' Status', 'STK', 'VAL', 'Minus Quantity', ],
}
WWW_NODES = {
    'fields': ['www_source_id', 'www_sub_source_id', 'www_node_id', 'date_active_from', 'date_active_to', 'active',
               'attribute1', 'attribute2', 'attribute3', 'attribute4', 'attribute5', 'attribute6', 'sl_no',
               'last_update_date', 'last_updated_by', 'creation_date', 'created_by', 'bu_id', 'delete_flag',
               'update_source', 'record_status', 'language_code', 'source_node_id', 'source_node_path', 'category',
               'sub_category', ],
    'headers': ['Www Source Id', 'Www Sub Source Id', 'Www Node Id', 'Date Active From', 'Date Active To', 'Active',
                'Attribute1', 'Attribute2', 'Attribute3', 'Attribute4', 'Attribute5', 'Attribute6', 'Sl No',
                'Last Update Date', 'Last Updated By', 'Creation Date', 'Created By', 'Bu Id', 'Delete Flag',
                'Update Source', 'Record Status', 'Language', 'Node ID', 'Node Desc', 'Category', 'Sub Category', ],
}
WWW_SOURCES = {
    'fields': ['www_source_id', 'date_active_from', 'date_active_to', 'active', 'attribute1', 'attribute2',
               'attribute3', 'attribute4', 'attribute5', 'attribute6', 'last_update_date', 'last_updated_by',
               'creation_date', 'created_by', 'bu_id', 'delete_flag', 'update_source', 'record_status',
               'www_source_name', 'www_source_desc', ],
    'headers': ['Www Source Id', 'Date Active From', 'Date Active To', 'Active', 'Attribute1', 'Attribute2',
                'Attribute3', 'Attribute4', 'Attribute5', 'Attribute6', 'Last Update Date', 'Last Updated By',
                'Creation Date', 'Created By', 'Bu Id', 'Delete Flag', 'Update Source', 'Record Status', 'Name',
                'Description', ],
}
WWW_SUB_SOURCES = {
    'fields': ['www_source_id', 'www_sub_source_id', 'date_active_from', 'date_active_to', 'active', 'attribute1',
               'attribute2', 'attribute3', 'attribute4', 'attribute5', 'attribute6', 'last_update_date',
               'last_updated_by', 'creation_date', 'created_by', 'bu_id', 'delete_flag', 'update_source',
               'record_status', 'sl_no', 'sub_source_name', 'country_code', 'language_code', ],
    'headers': ['Www Source Id', 'Www Sub Source Id', 'Date Active From', 'Date Active To', 'Active', 'Attribute1',
                'Attribute2', 'Attribute3', 'Attribute4', 'Attribute5', 'Attribute6', 'Last Update Date',
                'Last Updated By', 'Creation Date', 'Created By', 'Bu Id', 'Delete Flag', 'Update Source',
                'Record Status', 'Sl No', 'Name', 'Country', 'Language', ],
}
# , 'mkuptemp_id',
INV_MANUFACTURERS = {
    'fields': ['creation_date', 'created_by', 'bu_id', 'last_update_date', 'last_updated_by', 'record_status',
               'delete_flag', 'update_source', 'manf_id', 'manf_number', 'manf_name', 'manf_short_name', 'contact_name',
               'address_line1', 'city', 'county', 'post_code', 'country_code',
               'phone1', 'phone2', 'fax', 'mobile', 'email', 'www', 'attribute1', 'attribute2' ],
    'headers': ['Creation Date', 'Created By', 'Bu Id', 'Last Update Date', 'Last Updated By', 'Record Status',
                'Delete Flag', 'Update Source', 'ID', 'Number', 'Name', 'Short Name', 'Contact Name', 'Address ',
                'City',
                'County', 'Post Code', 'Country', 'Phone1', 'Phone2', 'Fax', 'Mobile', 'Email', 'WWW',
                'Attribute1', 'Attribute2', ],
}

AP_SUPPLIERS = {
    'fields': ['supplier_id', 'supplier_number', 'supplier_name', 'asp_sup_profile_id', 'short_name', 'ctc_tax_code_id',
               'currency_code', 'address_line1', 'city', 'county', 'post_code',
               'country_code', 'phone1', 'phone2', 'mobile', 'fax', 'email', 'contact_name', 'contact_name2',
               'cmc_pc_id', 'sup_vatregno', 'www', 'location_id', 'account_number', 'cpt_id', 'pmnt_method_id',
               'item_prefix', 'supplier_category_code', 'po_preference', 'po_condition', 'back_order_type',
               'po_allowed', 'order_cycle_type', 'order_qty_type', 'order_cycle', 'lead_time', 'safety_net_days',
               'min_order_amount', 'paid_amount', 'invoiced_amount', 'balance', 'supplier_hold', 'hold_reason',
               'orig_system_ref_hdr', 'mkuptemp_id', 'gac_gl_account_id', 'creation_date', 'bu_id', 'last_ordered_date',
               'record_status', 'last_update_date', 'last_updated_by', 'update_source', 'delete_flag', 'created_by',
               'primary_supplier_id', 'customer_id', 'attribute1', 'attribute2', ],
    'headers': ['ID', 'Number', 'Name', 'Profile', 'Short Name', 'Tax Code', 'Currency', 'Address ', 'City',
                'County', 'Post Code', 'Country', 'Phone1', 'Phone2', 'Mobile', 'Fax', 'Email', 'Contact Name',
                'Contact Name2', 'Container', 'Registration No.', 'WWW', 'Location', 'Account Number', 'Payment Term',
                'Payment Method', 'Item Prefix Code ', 'Category', 'PO Preference', 'PO Condition', 'Back Order',
                'PO Allowed', 'Order Cycle Type', 'Order Qty Type', 'Order Cycle(days)', 'Lead Time(days)',
                'Safety Net(days)', 'Min Order Amount', 'Paid Amount', 'Invoiced Amount', 'Balance', 'Hold', 'Reason',
                'System Reference', 'mkuptemp_id', 'Purchase GL Account', 'Creation Date', 'Bu Id', 'Last Ordered Date',
                'Record Status',
                'Last Update Date', 'Last Updated By', 'Update Source', 'Delete Flag', 'Created By',
                'Primary Supplier ID', 'Customer ID', 'Notes1', 'Notes2', ],
}