update cmn_functions set func_description='ITEM MOVEMENTS' Where func_name='INV_ITEMMOVEMENT01';
update cmn_functions set func_description='' Where func_name='INV_ITEMLOCQRY01';
update cmn_functions set func_description='PURCHASE ORDER' Where func_name='PO_PO01';
update cmn_functions set func_description='STOCK ADJUSTMENT' Where func_name='INV_STKADJUST01';
update cmn_functions set func_description='WEEE CHARGES' Where func_name='INV_WEEE01';
update cmn_functions set func_description='SUPPLUER PRICE LIST' Where func_name='AP_SUPPL01';
update cmn_functions set func_description='CUSTOMER PRICE LIST' Where func_name='AR_CUSTPL01';
update cmn_functions set func_description='CUSTOMER PAYMENT METHODS' Where func_name='AR_CUSTPM01';
update cmn_functions set func_description='/SETUP/TERMCOND_LIST/' Where func_name='CMN_TERMS01';
update cmn_functions set func_description='ITEM OFFERS' Where func_name='PRICE_OFFER01';
update cmn_functions set func_description='SIMILAR ITEMS' Where func_name='INV_SIMITEM01';
update cmn_functions set func_description='ITEM SERIAL NUMBERS' Where func_name='INV_SERIALNUM01';
update cmn_functions set func_description='/SETUP/CURRENCYRATES_LIST/' Where func_name='CMN_CURRATE01';
update cmn_functions set func_description='' Where func_name='INV_ITEMSEARCH01';
update cmn_functions set func_description='PRICE BREAKS' Where func_name='INV_PRICEBREAK01';
update cmn_functions set func_description='ADMIN/COMMON/' Where func_name='CMN_SEQUENCE01';
update cmn_functions set func_description='LOCATIONS' Where func_name='INV_LOCATION01';
update cmn_functions set func_description='MANUFACTURERS' Where func_name='INV_MANF01';
update cmn_functions set func_description='AP OPTIONS' Where func_name='AP_OPTIONS01';
update cmn_functions set func_description='AR OPTIONS' Where func_name='AR_OPTIONS01';
update cmn_functions set func_description='ADMIN/COMMON/' Where func_name='CMN_PRINTER01';
update cmn_functions set func_description='INV OPTIONS' Where func_name='INV_OPTIONS01';
update cmn_functions set func_description='/SETUP/CMNSYSOPTIONS_LIST/' Where func_name='SYS_OPTIONS01';
update cmn_functions set func_description='/SETUP/REASONS_LIST/' Where func_name='CMN_REASONS01';
update cmn_functions set func_description='/SETUP/CONTAINERS_LIST/' Where func_name='CMN_CONTAINER01';
update cmn_functions set func_description='SUPPLIERS' Where func_name='AP_SUP01';
update cmn_functions set func_description='SUPPLIER PROFILES' Where func_name='AP_SUPPROF01';
update cmn_functions set func_description='CUSTOMERS' Where func_name='AR_CUST01';
update cmn_functions set func_description='CUSTOMER PROFILES' Where func_name='AR_CUSTPROF01';
update cmn_functions set func_description='/SETUP/COUNTRIES_LIST/' Where func_name='CMN_COUNTRY01';
update cmn_functions set func_description='/SETUP/PMNTTERMS_LIST/' Where func_name='CMN_PMNTTERM01';
update cmn_functions set func_description='ITEM CATEGORIES' Where func_name='INV_CATEGORY01';
update cmn_functions set func_description='ITEMS' Where func_name='INV_ITEM01';
update cmn_functions set func_description='PRICE TYPES' Where func_name='INV_PRTYPE01';
update cmn_functions set func_description='/SETUP/SEASONS_LIST/' Where func_name='CMN_SEASON01';
update cmn_functions set func_description='/SETUP/BANKS_LIST/' Where func_name='CMN_BANK01';
update cmn_functions set func_description='/SETUP/BUSECTOR_LIST/' Where func_name='CMN_BUSECT01';
update cmn_functions set func_description='/SETUP/TAXCODES_LIST/' Where func_name='CMN_TAXCODE01';
update cmn_functions set func_description='/SETUP/CURRENCIES_LIST/' Where func_name='CMN_CUR01';
update cmn_functions set func_description='/SETUP/PMNTMENTOD_LIST/' Where func_name='CMN_PMT01';
update cmn_functions set func_description='UNIT OF MEASUREMENTS' Where func_name='CMN_UOM01';
update cmn_functions set func_description='/SETUP/BU_LIST/' Where func_name='CMN_BUS01';
update cmn_functions set func_description='/SETUP/COMPANY_LIST/' Where func_name='CMN_COMP01';
update cmn_functions set func_description='/SETUP/LOOKUP_LIST' Where func_name='CMN_LOOKUP01';
update cmn_functions set func_description='/SETUP/GLCODES_LIST/' Where func_name='GL_AC01';
update cmn_functions set func_description='ADMIN/COMMON/' Where func_name='CMN_RESP01';
update cmn_functions set func_description='/COMMON/LISTUSERS/' Where func_name='CMN_USER01';
update cmn_functions set func_description='ADMIN/COMMON/' Where func_name='CMN_MENU01';
update cmn_functions set func_description='/ADMIN/COMMON/' Where func_name='CMN_FUNCTION01';
update cmn_functions set func_description='/ENQUIRY/ARINVOICESUM/' Where func_name='AR_SUMINVOICE01';
update cmn_functions set func_description='/ADMIN/COMMON/' Where func_name='SYS_EXPTEMPLATE01';
update cmn_functions set func_description='ITEM BATCH' Where func_name='INV_ITEMBATCH01';
update cmn_functions set func_description='/SETUP/ALERTS_LIST/' Where func_name='CMN_ALERT01';
update cmn_functions set func_description='/SETUP/MAILMERGE_LIST/' Where func_name='CMN_MAILMERGE01';
update cmn_functions set func_description='ADMIN/COMMON/' Where func_name='SYS_USERCTRL01';
update cmn_functions set func_description='ADMIN/COMMON/' Where func_name='SYS_CONTROL01';
update cmn_functions set func_description='SALES INVOICE 02' Where func_name='AR_INVOICE02';
update cmn_functions set func_description='REPORT LOG' Where func_name='/reports/rwservlet/showjobs?server=rep_svr-oratech2';
update cmn_functions set func_description='TECHNET' Where func_name='HTTP://TECHNET.ORACLE.COM';
update cmn_functions set func_description='BBC' Where func_name='HTTP://WWW.BBC.CO.UK';
update cmn_functions set func_description='ORACLE' Where func_name='HTTP://WWW.ORACLE.COM';
update cmn_functions set func_description='ORATECH' Where func_name='HTTP://WWW.ORATECHSOLUTIONS.BIZ';
update cmn_functions set func_description='SALES PAYMENT BY INVOICE' Where func_name='AR_PMNTBYINV01';
update cmn_functions set func_description='/ADMIN/COMMON/SYSPROGRAMS/' Where func_name='SYS_PROGRAM01';
update cmn_functions set func_description='ADMIN/COMMON/' Where func_name='SYS_SCHEDULEDJOB01';
update cmn_functions set func_description='' Where func_name='SYS_COMPILE01';
update cmn_functions set func_description='' Where func_name='AR_INVBATCH01';
update cmn_functions set func_description='QUICK CODE SETUP' Where func_name='INV_QKCODE01';
update cmn_functions set func_description='ITEM QUICK MOVEMENT' Where func_name='INV_ITEMQKMVMNT01';
update cmn_functions set func_description='/SETUP/COMMCODE_LIST/' Where func_name='CMN_COMMODITY01';
update cmn_functions set func_description='SUB LOC ASSIGNMENT BATCH' Where func_name='INV_SLOCASSIGNBATCH01';
update cmn_functions set func_description='' Where func_name='GL_SUMCASHINGUP01';
update cmn_functions set func_description='' Where func_name='SYS_MISCTASK01';
update cmn_functions set func_description='MANUAL SALES INVOIE' Where func_name='AR_INVMANUAL01';
update cmn_functions set func_description='PURCHASE ORDER INTERNAL USAGE' Where func_name='PO_MANUALPO01';
update cmn_functions set func_description='/ENQUIRY/INTRATRADESUM/' Where func_name='AR_INTRASTATE01';
update cmn_functions set func_description='/ENQUIRY/REQSUM/' Where func_name='INV_SUMRQSTION01';
update cmn_functions set func_description='CREATE REQUISITION' Where func_name='INV_RQSTIONCR01';
update cmn_functions set func_description='FULFILL REQUISITION' Where func_name='INV_RQSTIONFL01';
update cmn_functions set func_description='RECEIVE REQUISITION' Where func_name='INV_RQSTIONGRN01';
update cmn_functions set func_description='IMPORT SALES ORDERS' Where func_name='AR_SALORDIMP01';
update cmn_functions set func_description='BARCODE REPOSITORY' Where func_name='INV_BARREPOSITORY01';
update cmn_functions set func_description='' Where func_name='INV_SUMSTKTAKE01';
update cmn_functions set func_description='UPDATE BIN IDENTIFIER' Where func_name='INV_BINIDENTIFIER01';
update cmn_functions set func_description='/MOBILE/ITEMSINSUBLOC/' Where func_name='spm_sublocitem?p_userid=$USERID$';
update cmn_functions set func_description='/ENQUIRY/SALESORDERLINES/' Where func_name='AR_SALORDLINEHIST01';
update cmn_functions set func_description='/MOBILE/FINDSALESORDER/' Where func_name='spm_arfindorder?p_userid=$USERID$';
update cmn_functions set func_description='/MOBILE/SALESORDERQUERY/' Where func_name='spm_arordqry?p_userid=$USERID$';
update cmn_functions set func_description='/MOBILE/GOODSDISTRIBUTE/' Where func_name='spm_grndistribute01?p_userid=$USERID$';
update cmn_functions set func_description='/ENQUIRY/SAGEQUERY/' Where func_name='AR_SAGEEXPORT01';
update cmn_functions set func_description='IMPORT CUSTOMERS' Where func_name='AR_CUSTIMP01';
update cmn_functions set func_description='/ENQUIRY/SALESINVOICELINES/' Where func_name='AR_INVLINEHIST01';
update cmn_functions set func_description='' Where func_name='spm_spacecheck?p_userid=$USERID$';
update cmn_functions set func_description='/MOBILE/MOVEITEM/' Where func_name='spm_movetoprimary?p_userid=$USERID$';
update cmn_functions set func_description='' Where func_name='INV_ITEMFREIGHTS01';
update cmn_functions set func_description='BILL OF MATERIALS' Where func_name='INV_BOM01';
update cmn_functions set func_description='MARKUP TEMPLATE' Where func_name='INV_MKUPTEMP01';
update cmn_functions set func_description='PRICE TEMPLATE' Where func_name='PRICE_TEMPLATE01';
update cmn_functions set func_description='/ENQUIRY/APINVOICESUM/' Where func_name='AP_SUMINV01';
update cmn_functions set func_description='' Where func_name='AP_SUPDRILLDOWN01';
update cmn_functions set func_description='/ENQUIRY/CUSTOMERDRILLDOWN/' Where func_name='AR_CUSTDRILLDOWN01';
update cmn_functions set func_description='/ENQUIRY/SALESORDERSUM/' Where func_name='AR_SUMSALORD01';
update cmn_functions set func_description='/MOBILE/RECEIVEREQUISITION/' Where func_name='spm_rqstiongrn01?p_userid=$USERID$';
update cmn_functions set func_description='/MOBILE/FULFILLREQUISITION/' Where func_name='spm_rqstionfl01?p_userid=$USERID$';
update cmn_functions set func_description='/MOBILE/DISPATCHES/' Where func_name='spm_dispatches?p_userid=$USERID$';
update cmn_functions set func_description='' Where func_name='GRN_SUMORDPAD01';
update cmn_functions set func_description='PURCHASE ORDER PAD' Where func_name='PO_ORDERPAD01';
update cmn_functions set func_description='' Where func_name='PO_SUMORDPAD01';
update cmn_functions set func_description='/ENQUIRY/ARINVOICESUM/' Where func_name='AR_INVLINESUM01';
update cmn_functions set func_description='/MOBILE/MANUALSTKTAKE/' Where func_name='spm_annstktake?p_userid=$USERID$';
update cmn_functions set func_description='/ENQUIRY/SALESORDERPICKLIST/' Where func_name='AR_SUMPICKLIST01';
update cmn_functions set func_description='SPLIT STOCK' Where func_name='INV_STOCKSPLIT01';
update cmn_functions set func_description='/ENQUIRY/ITEMCATEGORY/' Where func_name='INV_CATEGORYQRY01';
update cmn_functions set func_description='' Where func_name='SPM_MOVESUBLOCS?p_userid=$USERID$';
update cmn_functions set func_description='/MOBILE/INTERDEPOTMOVEMENT/' Where func_name='spm_interofficemovement?p_userid=$USERID$';
update cmn_functions set func_description='/MOBILE/PICKSALESORDER/' Where func_name='spm_arordpicklist?p_userid=$USERID$';
update cmn_functions set func_description='/MOBILE/INITIALSTKTAKE/' Where func_name='spm_inistktake?p_userid=$USERID$';
update cmn_functions set func_description='/MOBILE/STOCKADJUSTMENT/' Where func_name='spm_itemadjustment?p_userid=$USERID$';
update cmn_functions set func_description='/MOBILE/ITEMCOUNT/' Where func_name='spm_itemcount?p_userid=$USERID$';
update cmn_functions set func_description='/MOBILE/LOCATEANITEM/' Where func_name='spm_locateitem?p_userid=$USERID$';
update cmn_functions set func_description='/MOBILE/UPDATESUBLOCMINMAX/' Where func_name='spm_sublocminmax?p_userid=$USERID$';
update cmn_functions set func_description='/MOBILE/PRICECHECK/' Where func_name='spm_pricecheck?p_userid=$USERID$';
update cmn_functions set func_description='/MOBILE/CREATEGRN/' Where func_name='spm_GRN01?p_userid=$USERID$';
update cmn_functions set func_description='/MOBILE/EXTMOVEMENT/' Where func_name='spm_exttointmovement?p_userid=$USERID$';
update cmn_functions set func_description='/MOBILE/MOVEITEM/' Where func_name='spm_intmovement?p_userid=$USERID$';
update cmn_functions set func_description='HELP ORATECH' Where func_name='http://www.oratechsolutions.biz/oratechhelp/oratechmain.html';
update cmn_functions set func_description='/MOBILE/SODELVCONFIRMATION/' Where func_name='spm_arorddlv?p_userid=$USERID$';
update cmn_functions set func_description='/MOBILE/ADDITEMTOBATCH/' Where func_name='spm_additemtobatch?p_userid=$USERID$';
update cmn_functions set func_description='/MOBILE/SETPRIMARYSALES/' Where func_name='spm_setplbyitem?p_userid=$USERID$';
update cmn_functions set func_description='SPLIT GOODS IN' Where func_name='AR_SPLITORDER01';
update cmn_functions set func_description='/ENQUIRY/ITEMADJUSTMENT/' Where func_name='INV_SUMADJUST01';
update cmn_functions set func_description='PICKING ASSIGNMENTS' Where func_name='AR_SALORDASSIGN01';
update cmn_functions set func_description='/ENQUIRY/DISPATCHSUM/' Where func_name='WH_SUMDISPATCH01';
update cmn_functions set func_description='/MOBILE/MERGEPALLET/' Where func_name='spm_palletmerge?p_userid=$USERID$';
update cmn_functions set func_description='/MOBILE/SPLIT/PALLET/' Where func_name='spm_palletsplit?p_userid=$USERID$';
update cmn_functions set func_description='/MOBILE/PALLETMOVE/' Where func_name='spm_pallmoveitem01?p_userid=$USERID$';
update cmn_functions set func_description='/MOBILE/FINDPALLETS/' Where func_name='spm_palletqry01?p_userid=$USERID$';
update cmn_functions set func_description='MANAGE DISPATCHES' Where func_name='WH_DISPATCH01';
update cmn_functions set func_description='' Where func_name='AR_SALORDDASH01';
update cmn_functions set func_description='MANAGE BOX' Where func_name='PALLET_BOX01';
update cmn_functions set func_description='MANAGE PALLET' Where func_name='PALLET_CR01';
update cmn_functions set func_description='' Where func_name='AR_SUMORDPAD01';
update cmn_functions set func_description='SALES ORDER PAD' Where func_name='AR_SALORDERPAD01';
update cmn_functions set func_description='EXPORT DATA' Where func_name='SYS_EXPORT01';
update cmn_functions set func_description='EXPORT MAINTENANCE' Where func_name='EXP_MANAGE01';
update cmn_functions set func_description='IMPORT / EXPORT SETUP' Where func_name='IMPEXP_SETUP01';
update cmn_functions set func_description='QUICK SALES ORDER' Where func_name='AR_SALORDQK01';
update cmn_functions set func_description='/ENQUIRY/ITEMSTATUS/' Where func_name='INV_ITEMSTATUS01';
update cmn_functions set func_description='/MOBILE/UPDATEBIN/' Where func_name='spm_updatebin?p_userid=$USERID$';
update cmn_functions set func_description='/SETUP/WEBSOURCES_LIST/' Where func_name='WEB_SOURCES01';
update cmn_functions set func_description='' Where func_name='CMN_MULTILANG01';
update cmn_functions set func_description='' Where func_name='TP_FEEDS01';
update cmn_functions set func_description='/SETUP/LANGUAGES_LIST/' Where func_name='CMN_LANGUAGE01';
update cmn_functions set func_description='/ENQUIRY/COSTPRICEHIST/' Where func_name='INV_ITEMCPHIST02';
update cmn_functions set func_description='JOURNAL ENTRIES' Where func_name='GL_JE01';
update cmn_functions set func_description='GL TEMPLATE TRANS' Where func_name='GL_TEMPLATETRANS01';
update cmn_functions set func_description='GL TEMPLATES' Where func_name='GL_TEMPLATE01';
update cmn_functions set func_description='/MOBILE/ITEMINSUBLOC/' Where func_name='spm_iteminsubloc?p_userid=$USERID$';
update cmn_functions set func_description='/ENQUIRY/ITEMINSUBLOC/' Where func_name='INV_ITEMINSUBLOC01';
update cmn_functions set func_description='STYLE / DESIGN / PATTERNS' Where func_name='CMN_STYLEPATTERN01';
update cmn_functions set func_description='ADMIN/COMMON/' Where func_name='SYS_JOBQUEUE01';
update cmn_functions set func_description='' Where func_name='GL_TRANSSUM01';
update cmn_functions set func_description='SALES ORDER DELIVERY' Where func_name='AR_SALDLV01';
update cmn_functions set func_description='SALES ORDER PICKING' Where func_name='AR_SALPICK01';
update cmn_functions set func_description='/SETUP/WEBSITES_LIST/' Where func_name='CMN_WEBSITES01';
update cmn_functions set func_description='BULK UPDATE SP' Where func_name='PRICE_UPDATESP01';
update cmn_functions set func_description='IMPORT INVOICES' Where func_name='SYS_IMPORTTRANS01';
update cmn_functions set func_description='' Where func_name='CMN_CLOCKINAUDIT01';
update cmn_functions set func_description='CLOCK IN / OUT' Where func_name='CMN_CLOCKINOUT01';
update cmn_functions set func_description='RESERVED ITEMS' Where func_name='AR_RESERVE01';
update cmn_functions set func_description='' Where func_name='INV_ITEMDRILLDOWN01';
update cmn_functions set func_description='ADMIN/COMMON/' Where func_name='SYS_NOTIFEVENT01';
update cmn_functions set func_description='INTERNAL MOVEMENTS' Where func_name='INV_INTMOVEMENT01';
update cmn_functions set func_description='ADMIN/COMMON/' Where func_name='SYS_WLMNTN01';
update cmn_functions set func_description='CASHING UP' Where func_name='GL_CASHINGUP01';
update cmn_functions set func_description='PAYINN / PAYOUT' Where func_name='GL_PMNT01';
update cmn_functions set func_description='/ENQUIRY/DBNOTESUM/' Where func_name='AP_SUMDBNOTE01';
update cmn_functions set func_description='' Where func_name='PRICE_CHECK01';
update cmn_functions set func_description='SUB LOCATION ASSIGNMENTS' Where func_name='INV_SLOCASSIGN01';
update cmn_functions set func_description='' Where func_name='SYS_UICONFIG01';
update cmn_functions set func_description='/ADMIN/COMMON/SYSWORKLIST/' Where func_name='SYS_WORKLIST01';
update cmn_functions set func_description='ADMIN/COMMON/' Where func_name='CMN_TERMINAL01';
update cmn_functions set func_description='SALES CREDIT NOTE' Where func_name='AR_CRNOTE01';
update cmn_functions set func_description='ITEM MASS UPDATE' Where func_name='INV_ITEMMASS01';
update cmn_functions set func_description='/ADMIN/COMMON/' Where func_name='CMN_GRANTPRIV01';
update cmn_functions set func_description='ADMIN/COMMON/' Where func_name='CMN_PRIV01';
update cmn_functions set func_description='ADMIN/COMMON/' Where func_name='CMN_PROFVAL01';
update cmn_functions set func_description='ADMIN/COMMON/' Where func_name='CMN_PROF01';
update cmn_functions set func_description='' Where func_name='AUD_MINUSSTOCK01';
update cmn_functions set func_description='ADMIN/COMMON/' Where func_name='CMN_REPGROUP01';
update cmn_functions set func_description='/ENQUIRY/ITEMMOVEMENTS/' Where func_name='INV_SUMMOVEMENT01';
update cmn_functions set func_description='SALES PAYMENTS' Where func_name='AR_PMNTBYMETHOD01';
update cmn_functions set func_description='FREIGHT SETUP' Where func_name='AR_FREIGHT01';
update cmn_functions set func_description='BULK UPDATE CP' Where func_name='PRICE_UPDATECP01';
update cmn_functions set func_description='/ENQUIRY/COSTPRICEHIST/' Where func_name='INV_ITEMCPHIST01';
update cmn_functions set func_description='/ENQUIRY/GRNSUM/' Where func_name='PO_SUMGRN01';
update cmn_functions set func_description='/ENQUIRY/POSUM/' Where func_name='PO_SUMPO01';
update cmn_functions set func_description='SALES INVOICE' Where func_name='AR_INVOICE01';
update cmn_functions set func_description='DELIVERY NOTE' Where func_name='AR_DELNOTE01';
update cmn_functions set func_description='SALES CREDIT GROUPS' Where func_name='AR_SALCRGROUP01';
update cmn_functions set func_description='SALES PERSONS' Where func_name='AR_SALESPERSON01';
update cmn_functions set func_description='SALES ORDER' Where func_name='AR_SALORD01';
update cmn_functions set func_description='PRICE LIST' Where func_name='PRICE_LIST01';
update cmn_functions set func_description='' Where func_name='CMN_PERIOD01';
update cmn_functions set func_description='' Where func_name='INV_SUMITEMCOUNT01';
update cmn_functions set func_description='/ENQUIRY/ITEMTRANSHIST/' Where func_name='INV_ITEMHIST01';
update cmn_functions set func_description='/ADMIN/COMMON/SYSSCHEDULEJOBS/' Where func_name='SYS_SCHJOB01';
update cmn_functions set func_description='' Where func_name='INV_ITEMSLOCSNAP01';
update cmn_functions set func_description='/ADMIN/COMMON/' Where func_name='SYS_FUNCAUDIT01';
update cmn_functions set func_description='ADMIN/COMMON/' Where func_name='SYS_LOGAUDIT01';
update cmn_functions set func_description='ADMIN/COMMON/' Where func_name='SYS_SCHEDULE01';
update cmn_functions set func_description='DEBIT NOTES' Where func_name='AP_DBNOTE01';
update cmn_functions set func_description='ITEM DIMENSIONS' Where func_name='INV_ITEMDIM01';
update cmn_functions set func_description='EMPLOYEES' Where func_name='EMP_EMP01';
update cmn_functions set func_description='JOB TYPES' Where func_name='EMP_JOBTYPE01';
update cmn_functions set func_description='WORKING DAYS' Where func_name='EMP_WDAY01';
update cmn_functions set func_description='DEPARTMENTS' Where func_name='EMP_DEPT01';
update cmn_functions set func_description='JOBS' Where func_name='EMP_JOB01';
update cmn_functions set func_description='POSITIONS' Where func_name='EMP_POS01';
update cmn_functions set func_description='ADD ITEM TO LOCATION' Where func_name='INV_ITEMADDTOLOC01';
update cmn_functions set func_description='' Where func_name='SYS_RUNPROCESS01';
update cmn_functions set func_description='ADMIN/COMMON/' Where func_name='SYS_LOG01';
update cmn_functions set func_description='PAYMENTS' Where func_name='AP_PAYMENT01';
update cmn_functions set func_description='INVOICE' Where func_name='AP_INV01';
update cmn_functions set func_description='' Where func_name='CMN_PROPERTYVAL01';
update cmn_functions set func_description='' Where func_name='CMN_PROPERTY01';
update cmn_functions set func_description='' Where func_name='SYS_IMPORT01';
update cmn_functions set func_description='ITEM COUNTS' Where func_name='INV_STKCOUNT01';
update cmn_functions set func_description='STOCK TAKE ITEMS' Where func_name='INV_STKTAKEITEM01';
update cmn_functions set func_description='STOCK TAKE TYPES' Where func_name='INV_STKTAKETYPE01';
update cmn_functions set func_description='' Where func_name='SYS_ADMIN01';
update cmn_functions set func_description='PREFERRED SUPPLIER' Where func_name='AP_PREFSUPITEM01';
update cmn_functions set func_description='GOODS RECEIPT' Where func_name='PO_GRN01';
update cmn_functions set func_description='REPORTS' Where func_name='SYS_REPORTS01';
update cmn_functions set func_description='/ENQUIRY/ITEMINLOC/' Where func_name='INV_ITEMINLOC01';
update cmn_functions set func_description='' Where func_name='CMN_PRROUND01';
update cmn_functions set func_description='PO BUYERS' Where func_name='PO_BUYERS01';