import datetime
import os
from django.db import models
from django.db.models import Count, Sum, Min, Max
from django.contrib.auth.models import User
from django.urls import reverse
from common.sysutil  import *
from common.translation import  (VN_C, VN_T)
from common import commonutil



class ImpItems(models.Model):
    sub_category_name5 = models.CharField(max_length=100, blank=True, null=True, verbose_name=VN_C('sub_category_name5'))
    media1 = models.CharField(max_length=250, blank=True, null=True, verbose_name=VN_C('media1'))
    media2 = models.CharField(max_length=250, blank=True, null=True, verbose_name=VN_C('media2'))
    media3 = models.CharField(max_length=250, blank=True, null=True, verbose_name=VN_C('media3'))
    media4 = models.CharField(max_length=250, blank=True, null=True, verbose_name=VN_C('media4'))
    country_of_manf = models.CharField(max_length=100, blank=True, null=True, verbose_name=VN_C('country_of_manf'))
    country_of_origin = models.CharField(max_length=100, blank=True, null=True, verbose_name=VN_C('country_of_origin'))
    click_and_collect = models.CharField(max_length=1, blank=True, null=True, verbose_name=VN_C('click_and_collect'))
    delivery = models.CharField(max_length=1, blank=True, null=True, verbose_name=VN_C('delivery'))
    status_code = models.CharField(max_length=30, blank=True, null=True, verbose_name=VN_C('status_code'))
    status_message = models.CharField(max_length=4000, blank=True, null=True, verbose_name=VN_C('status_message'))
    start_date_active = models.DateTimeField(blank=True, null=True, verbose_name=VN_C('start_date_active'))
    balancesheet_gl_account_id = models.IntegerField(blank=True, null=True, editable=False, verbose_name=VN_C('balancesheet_gl_account_id'))
    pnl_gl_account_id = models.IntegerField(blank=True, null=True, editable=False, verbose_name=VN_C('pnl_gl_account_id'))
    pricevariance_gl_account_id = models.IntegerField(blank=True, null=True, editable=False, verbose_name=VN_C('pricevariance_gl_account_id'))
    costofsales_gl_account_id = models.IntegerField(blank=True, null=True, editable=False, verbose_name=VN_C('costofsales_gl_account_id'))
    sales_gl_account_id = models.IntegerField(blank=True, null=True, editable=False, verbose_name=VN_C('sales_gl_account_id'))
    inner_qty = models.DecimalField(max_digits=12, decimal_places=3,blank=True, null=True, verbose_name=VN_C('inner_qty'))
    picturename3 = models.CharField(max_length=150, blank=True, null=True, verbose_name=VN_C('picturename3'))
    picturename2 = models.CharField(max_length=150, blank=True, null=True, verbose_name=VN_C('picturename2'))
    picturename1 = models.CharField(max_length=150, blank=True, null=True, verbose_name=VN_C('picturename1'))
    technical_specs_file = models.CharField(max_length=240, blank=True, null=True, verbose_name=VN_C('technical_specs_file'))
    technical_specs = models.CharField(max_length=2000, blank=True, null=True, verbose_name=VN_C('technical_specs'))
    demo_video_file = models.CharField(max_length=240, blank=True, null=True, verbose_name=VN_C('demo_video_file'))
    freight_price_criteria = models.CharField(max_length=10, blank=True, null=True, verbose_name=VN_C('freight_price_criteria'))
    freight = models.CharField(max_length=1, blank=True, null=True, verbose_name=VN_C('freight'))
    take_snapshot = models.CharField(max_length=1, blank=True, null=True, verbose_name=VN_C('take_snapshot'))
    similar_item_concated = models.CharField(max_length=4000, blank=True, null=True, verbose_name=VN_C('similar_item_concated'))
    enforce_tax_code = models.CharField(max_length=1, blank=True, null=True, verbose_name=VN_C('enforce_tax_code'))
    apply_offer = models.CharField(max_length=1, blank=True, null=True, verbose_name=VN_C('apply_offer'))
    enforce_reorder_qty = models.CharField(max_length=1, blank=True, null=True, verbose_name=VN_C('enforce_reorder_qty'))
    external_reference = models.CharField(max_length=30, blank=True, null=True, verbose_name=VN_C('external_reference'))
    supplier_case_cp = models.DecimalField(max_digits=12, decimal_places=3,blank=True, null=True, verbose_name=VN_C('supplier_case_cp'))
    supplier_unit_cp = models.DecimalField(max_digits=12, decimal_places=3,blank=True, null=True, verbose_name=VN_C('supplier_unit_cp'))
    delivery_charges = models.DecimalField(max_digits=12, decimal_places=3,blank=True, null=True, verbose_name=VN_C('delivery_charges'))
    ccc_id = models.IntegerField(blank=True, null=True, editable=False, verbose_name=VN_C('ccc_id'))
    min_pb_qty = models.DecimalField(max_digits=12, decimal_places=3,blank=True, null=True, verbose_name=VN_C('min_pb_qty'))
    mkuptemp_id = models.IntegerField(blank=True, null=True, editable=False, verbose_name=VN_C('mkuptemp_id'))
    publish_to_web = models.CharField(max_length=1, blank=True, null=True, verbose_name=VN_C('publish_to_web'))
    key_words = models.CharField(max_length=2000, blank=True, null=True, verbose_name=VN_C('key_words'))
    replenished_from_location = models.IntegerField(blank=True, null=True, verbose_name=VN_C('replenished_from_location'))
    replenishment_options = models.CharField(max_length=30, blank=True, null=True, verbose_name=VN_C('replenishment_options'))
    default_label_name = models.CharField(max_length=100, blank=True, null=True, verbose_name=VN_C('default_label_name'))
    exchange_rate = models.DecimalField(max_digits=12, decimal_places=6,blank=True, null=True, verbose_name=VN_C('exchange_rate'))
    instrunction = models.CharField(max_length=400, blank=True, null=True, verbose_name=VN_C('instrunction'))
    image_hint = models.CharField(max_length=30, blank=True, null=True, verbose_name=VN_C('image_hint'))
    item_condition = models.CharField(max_length=30, blank=True, null=True, verbose_name=VN_C('item_condition'))
    stp_id = models.IntegerField(blank=True, null=True, editable=False, verbose_name=VN_C('stp_id'))
    stp_level6_id = models.IntegerField(blank=True, null=True, editable=False, verbose_name=VN_C('stp_level6_id'))
    stp_level5_id = models.IntegerField(blank=True, null=True, editable=False, verbose_name=VN_C('stp_level5_id'))
    stp_level4_id = models.IntegerField(blank=True, null=True, editable=False, verbose_name=VN_C('stp_level4_id'))
    stp_level3_id = models.IntegerField(blank=True, null=True, editable=False, verbose_name=VN_C('stp_level3_id'))
    stp_level2_id = models.IntegerField(blank=True, null=True, editable=False, verbose_name=VN_C('stp_level2_id'))
    stp_level1_id = models.IntegerField(blank=True, null=True, editable=False, verbose_name=VN_C('stp_level1_id'))
    freight_name = models.CharField(max_length=100, blank=True, null=True, verbose_name=VN_C('freight_name'))
    freight_line_id = models.IntegerField(blank=True, null=True, editable=False, verbose_name=VN_C('freight_line_id'))
    www_design_pattern = models.CharField(max_length=100, blank=True, null=True, verbose_name=VN_C('www_design_pattern'))
    www_package_quantity = models.CharField(max_length=100, blank=True, null=True, verbose_name=VN_C('www_package_quantity'))
    www_variation_theme = models.CharField(max_length=100, blank=True, null=True, verbose_name=VN_C('www_variation_theme'))
    www_relationship_type = models.CharField(max_length=100, blank=True, null=True, verbose_name=VN_C('www_relationship_type'))
    unit_volumetric_weight = models.DecimalField(max_digits=12, decimal_places=6,blank=True, null=True, verbose_name=VN_C('unit_volumetric_weight'))
    www_barcode_type = models.CharField(max_length=30, blank=True, null=True, verbose_name=VN_C('www_barcode_type'))
    www_parent_sku = models.CharField(max_length=100, blank=True, null=True, verbose_name=VN_C('www_parent_sku'))
    case_volumetric_weight = models.DecimalField(max_digits=12, decimal_places=6,blank=True, null=True, verbose_name=VN_C('case_volumetric_weight'))
    web_expedite_flag = models.CharField(max_length=150, blank=True, null=True, verbose_name=VN_C('web_expedite_flag'))
    www_parentage = models.CharField(max_length=100, blank=True, null=True, verbose_name=VN_C('www_parentage'))
    min_max_cal_type = models.CharField(max_length=30, blank=True, null=True, verbose_name=VN_C('min_max_cal_type'))
    typical_daily_usage = models.DecimalField(max_digits=13, decimal_places=3,blank=True, null=True, verbose_name=VN_C('typical_daily_usage'))
    virtual_stock = models.DecimalField(max_digits=12, decimal_places=3,blank=True, null=True, verbose_name=VN_C('virtual_stock'))
    sales_price_flag = models.CharField(max_length=30, blank=True, null=True, verbose_name=VN_C('sales_price_flag'))
    uom_id = models.IntegerField(blank=True, null=True, editable=False, verbose_name=VN_C('uom_id'))
    third_party_source = models.CharField(max_length=30, blank=True, null=True, verbose_name=VN_C('third_party_source'))
    third_party_source_ref = models.CharField(max_length=50, blank=True, null=True, verbose_name=VN_C('third_party_source_ref'))
    primary_barcode = models.CharField(max_length=30, blank=True, null=True, verbose_name=VN_C('primary_barcode'))
    category_name = models.CharField(max_length=100, blank=True, null=True, verbose_name=VN_C('category_name'))
    sub_category_name = models.CharField(max_length=100, blank=True, null=True, verbose_name=VN_C('sub_category_name'))
    tax_code = models.CharField(max_length=30, blank=True, null=True, verbose_name=VN_C('tax_code'))
    tax_rate = models.DecimalField(max_digits=5, decimal_places=3,blank=True, null=True, verbose_name=VN_C('tax_rate'))
    supplier_name = models.CharField(max_length=100, blank=True, null=True, verbose_name=VN_C('supplier_name'))
    manf_name = models.CharField(max_length=100, blank=True, null=True, verbose_name=VN_C('manf_name'))
    uom = models.CharField(max_length=30, blank=True, null=True, verbose_name=VN_C('uom'))
    sales_unit = models.IntegerField(blank=True, null=True, default=1, verbose_name=VN_C('sales_unit'))
    barcode1 = models.CharField(max_length=30, blank=True, null=True, verbose_name=VN_C('barcode1'))
    barcode2 = models.CharField(max_length=30, blank=True, null=True, verbose_name=VN_C('barcode2'))
    barcode3 = models.CharField(max_length=30, blank=True, null=True, verbose_name=VN_C('barcode3'))
    barcode4 = models.CharField(max_length=30, blank=True, null=True, verbose_name=VN_C('barcode4'))
    barcode5 = models.CharField(max_length=30, blank=True, null=True, verbose_name=VN_C('barcode5'))
    price_template = models.CharField(max_length=30, blank=True, null=True, verbose_name=VN_C('price_template'))
    item_batch_name = models.CharField(max_length=100, blank=True, null=True, verbose_name=VN_C('item_batch_name'))
    sub_category_name1 = models.CharField(max_length=100, blank=True, null=True, verbose_name=VN_C('sub_category_name1'))
    sub_category_name2 = models.CharField(max_length=100, blank=True, null=True, verbose_name=VN_C('sub_category_name2'))
    sub_category_name3 = models.CharField(max_length=100, blank=True, null=True, verbose_name=VN_C('sub_category_name3'))
    sub_category_name4 = models.CharField(max_length=100, blank=True, null=True, verbose_name=VN_C('sub_category_name4'))
    item_status = models.CharField(max_length=30, blank=True, null=True, verbose_name=VN_C('item_status'))
    iwc_charge_id = models.IntegerField(blank=True, null=True, editable=False, verbose_name=VN_C('iwc_charge_id'))
    update_source = models.CharField(max_length=30, blank=True, null=True, editable=False, verbose_name=VN_C('update_source'))
    ipbh_price_break_id = models.IntegerField(blank=True, null=True, editable=False, verbose_name=VN_C('ipbh_price_break_id'))
    pallet_qty = models.DecimalField(max_digits=12, decimal_places=3,blank=True, null=True, verbose_name=VN_C('pallet_qty'))
    item_comment = models.CharField(max_length=1000, blank=True, null=True, verbose_name=VN_C('item_comment'))
    item_specifications = models.CharField(max_length=1000, blank=True, null=True, verbose_name=VN_C('item_specifications'))
    supplier_notes3 = models.CharField(max_length=1000, blank=True, null=True, verbose_name=VN_C('supplier_notes3'))
    supplier_notes2 = models.CharField(max_length=1000, blank=True, null=True, verbose_name=VN_C('supplier_notes2'))
    supplier_notes1 = models.CharField(max_length=1000, blank=True, null=True, verbose_name=VN_C('supplier_notes1'))
    customer_notes3 = models.CharField(max_length=1000, blank=True, null=True, verbose_name=VN_C('customer_notes3'))
    customer_notes2 = models.CharField(max_length=1000, blank=True, null=True, verbose_name=VN_C('customer_notes2'))
    customer_notes1 = models.CharField(max_length=1000, blank=True, null=True, verbose_name=VN_C('customer_notes1'))
    case_cp = models.DecimalField(max_digits=14, decimal_places=3,blank=True, null=True, verbose_name=VN_C('case_cp'))
    item_style = models.CharField(max_length=50, blank=True, null=True, verbose_name=VN_C('item_style'))
    item_fitting = models.CharField(max_length=20, blank=True, null=True, verbose_name=VN_C('item_fitting'))
    item_size = models.CharField(max_length=100, blank=True, null=True, verbose_name=VN_C('item_size'))
    item_colour = models.CharField(max_length=30, blank=True, null=True, verbose_name=VN_C('item_colour'))
    goodsin_location_id = models.IntegerField(blank=True, null=True, editable=False, verbose_name=VN_C('goodsin_location_id'))
    sales_location_id = models.IntegerField(blank=True, null=True, editable=False, verbose_name=VN_C('sales_location_id'))
    gross_unit_weight = models.DecimalField(max_digits=12, decimal_places=6,blank=True, null=True, verbose_name=VN_C('gross_unit_weight'))
    gross_case_weight = models.DecimalField(max_digits=13, decimal_places=3,blank=True, null=True, verbose_name=VN_C('gross_case_weight'))
    gac_gl_account_id = models.IntegerField(blank=True, null=True, editable=False, verbose_name=VN_C('gac_gl_account_id'))
    cmc_pc_id = models.BigIntegerField(blank=True, null=True, editable=False, verbose_name=VN_C('cmc_pc_id'))
    sup_supplier_id = models.IntegerField(blank=True, null=True, editable=False, verbose_name=VN_C('sup_supplier_id'))
    im_manf_id = models.IntegerField(blank=True, null=True, editable=False, verbose_name=VN_C('im_manf_id'))
    ctc_tax_code_id = models.IntegerField(blank=True, null=True, editable=False, verbose_name=VN_C('ctc_tax_code_id'))
    warranty_period = models.CharField(max_length=20, blank=True, null=True, verbose_name=VN_C('warranty_period'))
    group4 = models.CharField(max_length=30, blank=True, null=True, verbose_name=VN_C('group4'))
    group3 = models.CharField(max_length=30, blank=True, null=True, verbose_name=VN_C('group3'))
    group2 = models.CharField(max_length=30, blank=True, null=True, verbose_name=VN_C('group2'))
    group1 = models.CharField(max_length=30, blank=True, null=True, verbose_name=VN_C('group1'))
    whose_for = models.CharField(max_length=20, blank=True, null=True, verbose_name=VN_C('whose_for'))
    iisc_sub_category_id = models.IntegerField(blank=True, null=True, editable=False, verbose_name=VN_C('iisc_sub_category_id'))
    iic_category_id = models.IntegerField(blank=True, null=True, editable=False, verbose_name=VN_C('iic_category_id'))
    sales_location_qty = models.DecimalField(max_digits=12, decimal_places=3,blank=True, null=True, verbose_name=VN_C('sales_location_qty'))
    reservable = models.CharField(max_length=1, blank=True, null=True, verbose_name=VN_C('reservable'))
    net_ingredient = models.DecimalField(max_digits=12, decimal_places=3,blank=True, null=True, verbose_name=VN_C('net_ingredient'))
    flagindateto = models.DateTimeField(blank=True, null=True, verbose_name=VN_C('flagindateto'))
    flagindatefrom = models.DateTimeField(blank=True, null=True, verbose_name=VN_C('flagindatefrom'))
    flaginwebexport = models.CharField(max_length=1, blank=True, null=True, verbose_name=VN_C('flaginwebexport'))
    print_picture = models.CharField(max_length=1, blank=True, null=True, verbose_name=VN_C('print_picture'))
    net_case_weight = models.DecimalField(max_digits=12, decimal_places=6,blank=True, null=True, verbose_name=VN_C('net_case_weight'))
    net_unit_weight = models.DecimalField(max_digits=12, decimal_places=6,blank=True, null=True, verbose_name=VN_C('net_unit_weight'))
    warrantied = models.CharField(max_length=1, blank=True, null=True, verbose_name=VN_C('warrantied'))
    serial_numbered = models.CharField(max_length=1, blank=True, null=True, verbose_name=VN_C('serial_numbered'))
    serviceditem = models.CharField(max_length=1, blank=True, null=True, verbose_name=VN_C('serviceditem'))
    stockable = models.CharField(max_length=1, blank=True, null=True, verbose_name=VN_C('stockable'))
    saleable = models.CharField(max_length=1, blank=True, null=True, verbose_name=VN_C('saleable'))
    purchaseable = models.CharField(max_length=1, blank=True, null=True, verbose_name=VN_C('purchaseable'))
    volume_uomid = models.IntegerField(blank=True, null=True, editable=False, verbose_name=VN_C('volume_uomid'))
    weight_uomid = models.IntegerField(blank=True, null=True, editable=False, verbose_name=VN_C('weight_uomid'))
    unit_volume = models.DecimalField(max_digits=9, decimal_places=3,blank=True, null=True, verbose_name=VN_C('unit_volume'))
    unit_height = models.DecimalField(max_digits=9, decimal_places=3,blank=True, null=True, verbose_name=VN_C('unit_height'))
    unit_width = models.DecimalField(max_digits=9, decimal_places=3,blank=True, null=True, verbose_name=VN_C('unit_width'))
    unit_length = models.DecimalField(max_digits=9, decimal_places=3,blank=True, null=True, verbose_name=VN_C('unit_length'))
    case_volume = models.DecimalField(max_digits=9, decimal_places=3,blank=True, null=True, verbose_name=VN_C('case_volume'))
    case_height = models.DecimalField(max_digits=9, decimal_places=3,blank=True, null=True, verbose_name=VN_C('case_height'))
    case_width = models.DecimalField(max_digits=9, decimal_places=3,blank=True, null=True, verbose_name=VN_C('case_width'))
    case_length = models.DecimalField(max_digits=9, decimal_places=3,blank=True, null=True, verbose_name=VN_C('case_length'))
    similar_item_id = models.IntegerField(blank=True, null=True, editable=False, verbose_name=VN_C('similar_item_id'))
    weighed_item = models.CharField(max_length=1, blank=True, null=True, verbose_name=VN_C('weighed_item'))
    alternate_unit_cp = models.DecimalField(max_digits=14, decimal_places=3,blank=True, null=True, verbose_name=VN_C('alternate_unit_cp'))
    alternate_case_cp = models.DecimalField(max_digits=14, decimal_places=3,blank=True, null=True, verbose_name=VN_C('alternate_case_cp'))
    qtyinstock = models.DecimalField(max_digits=12, decimal_places=3,blank=True, null=True, verbose_name=VN_C('qtyinstock'))
    item_name = models.CharField(max_length=150, blank=True, null=True, verbose_name=VN_C('item_name'))
    short_desc = models.CharField(max_length=50, blank=True, null=True, verbose_name=VN_C('short_desc'))
    opening_balance = models.DecimalField(max_digits=12, decimal_places=3,blank=True, null=True, verbose_name=VN_C('opening_balance'))
    item_id = models.IntegerField(blank=True, null=True, editable=False, verbose_name=VN_C('item_id'))
    record_status = models.CharField(max_length=1, blank=True, null=True, editable=False, verbose_name=VN_C('record_status'))
    last_updated_by = models.BigIntegerField(blank=True, null=True, editable=False, verbose_name=VN_C('last_updated_by'))
    last_update_date = models.DateTimeField(auto_now=True, blank=True, null=True, editable=False, verbose_name=VN_C('last_update_date'))
    track_usage = models.CharField(max_length=1, blank=True, null=True, verbose_name=VN_C('track_usage'))
    supplier_product_code = models.CharField(max_length=30, blank=True, null=True, verbose_name=VN_C('supplier_product_code'))
    picturetype = models.CharField(max_length=20, blank=True, null=True, verbose_name=VN_C('picturetype'))
    picturename = models.CharField(max_length=100, blank=True, null=True, verbose_name=VN_C('picturename'))
    season_code_id = models.IntegerField(blank=True, null=True, editable=False, verbose_name=VN_C('season_code_id'))
    closing_balance = models.DecimalField(max_digits=12, decimal_places=3,blank=True, null=True, verbose_name=VN_C('closing_balance'))
    creation_date = models.DateTimeField(auto_now_add=True, blank=True, null=True, editable=False, verbose_name=VN_C('creation_date'))
    created_by = models.BigIntegerField(blank=True, null=True, editable=False, verbose_name=VN_C('created_by'))
    delete_flag = models.CharField(max_length=1, blank=True, null=True, default='N', editable=False, verbose_name=VN_C('delete_flag'))
    long_desc = models.CharField(max_length=1000, blank=True, null=True, verbose_name=VN_C('long_desc'))
    bu_id = models.IntegerField(blank=True, null=True, editable=False, verbose_name=VN_C('bu_id'))
    item_number = models.CharField(max_length=50, blank=True, null=True, verbose_name=VN_C('item_number'))
    stock_holding_unit = models.IntegerField(blank=True, null=True, verbose_name=VN_C('stock_holding_unit'))
    unit_cp = models.DecimalField(max_digits=14, decimal_places=3,blank=True, null=True, verbose_name=VN_C('unit_cp'))
    case_unit = models.IntegerField(blank=True, null=True, verbose_name=VN_C('case_unit'))
    reorder_uomid = models.IntegerField(blank=True, null=True, editable=False, verbose_name=VN_C('reorder_uomid'))
    reorder_qty = models.DecimalField(max_digits=12, decimal_places=3,blank=True, null=True, verbose_name=VN_C('reorder_qty'))
    reorder_interval = models.IntegerField(blank=True, null=True, verbose_name=VN_C('reorder_interval'))
    max_qty = models.DecimalField(max_digits=12, decimal_places=3,blank=True, null=True, verbose_name=VN_C('max_qty'))
    min_qty = models.DecimalField(max_digits=12, decimal_places=3,blank=True, null=True, verbose_name=VN_C('min_qty'))
    stock_take_category = models.CharField(max_length=30, blank=True, null=True, verbose_name=VN_C('stock_take_category'))
    item_class_category = models.CharField(max_length=30, blank=True, null=True, verbose_name=VN_C('item_class_category'))
    item_dimension_type = models.CharField(max_length=30, blank=True, null=True, verbose_name=VN_C('item_dimension_type'))
    item_dimension = models.CharField(max_length=1, blank=True, null=True, verbose_name=VN_C('item_dimension'))
    valuable = models.CharField(max_length=1, blank=True, null=True, verbose_name=VN_C('valuable'))
    in_store = models.CharField(max_length=1, blank=True, null=True, verbose_name=VN_C('in_store'))
    trading_casecp = models.DecimalField(max_digits=12, decimal_places=3,blank=True, null=True, verbose_name=VN_C('trading_casecp'))
    trading_unitcp = models.DecimalField(max_digits=12, decimal_places=3,blank=True, null=True, verbose_name=VN_C('trading_unitcp'))
    average_unitcp = models.DecimalField(max_digits=12, decimal_places=3,blank=True, null=True, verbose_name=VN_C('average_unitcp'))
    retail_price  = models.DecimalField(max_digits=12, decimal_places=3,blank=True, null=True, verbose_name=VN_C('retail_price'))
    last_bought_unitcp = models.DecimalField(max_digits=12, decimal_places=3,blank=True, null=True, verbose_name=VN_C('last_bought_unitcp'))
    end_date_active = models.DateTimeField(blank=True, null=True, verbose_name=VN_C('end_date_active'))
    imp_item_id = models.BigIntegerField( blank=False, null=False, primary_key=True, verbose_name=VN_C('imp_item_id'))
    run_id = models.CharField(max_length=100, blank=False, null=False,  verbose_name=VN_C('run_id'))
    barcoderep = models.CharField(max_length=1, blank=True, null=True, verbose_name=VN_C('barcoderep'))
    ebay_node = models.CharField(max_length=400, blank=True, null=True, verbose_name=VN_C('ebay_node'))
    amazon_node = models.CharField(max_length=400, blank=True, null=True, verbose_name=VN_C('amazon_node'))
    key_value = models.TextField( blank=True, null=True, verbose_name=VN_C('key_value'))
    #tenant_id = models.IntegerField(blank=False, null=False,default=-1)

    class Meta:
        managed = False
        db_table = 'imp_items'
        verbose_name=VN_T('imp_items')

    def __str__(self):
        return self.item_number